### ISSUE TITLE
erreur de compilation namespace vide

### ISSUE THREAD

**Issue by posykrat** [alsacreations/KNACSS#132]
Salut salut,

Avec la v4.2.0 je n'arrive plus à compiler les fichiers Less qui utilisent des helper de Knacss (.inbl,.txtcenter,.line,...) sans renseigner le namespace.

Si je laisse par défaut : @kna-namespace:~""; -> plantage, le compilateur ne trouve pas les références
Si je change par  @kna-namespace:~"toto"; -> c'est ok

Bon, en soit c'est pas très dérangeant, mais pour la rétrocompatibilité c'est pas top.

Je compile avec Grunt et grunt-contrib-less.

**Comment by GaetanBt** [comment]
Je crois que c'est @magsout qui est à l'origine de ce code

**Comment by raphaelgoetter** [comment]
C'est bizarre.

Pour info, je compile généralement avec Prepros.io (je viens de retester avec et sans variable), et je viens de tester avec Gulp (gulp-less) et ça fonctionne aussi.

**Comment by posykrat** [comment]
Bon si on trouve une solution tant mieux, sinon je remplis la variable !
Merci pour les retours rapides.

**Comment by zouloux** [comment]
Je confirme, impossible de compiler des fichiers less contenant des helpers tels que .inbl si le namespace est laissé vide (~"").
J'ai cependant réussi à compiler avec le namespace ~"test" en utilisant .testinbl

**Comment by zouloux** [comment]
On dirait qu'il y a une erreur ligne 22 dans _06-helpers.less :
```
@kna-namespace
.@{kna-namespace}w33 {
	width: 33.3333%;
}

```

**Comment by raphaelgoetter** [comment]
Est-il possible que ce soit un bug de grunt-contrib-less ?

Ou une permissivité trop poussée de Prepros ou gulp-less qui - eux - fonctionnent très bien avec la variable laissée vide ?

**Comment by raphaelgoetter** [comment]
@zouloux je ne vois rien d'anormal : 
https://github.com/raphaelgoetter/KNACSS/blob/master/less/_06-helpers.less#L22

```css
.@{kna-namespace}w30 {
	width: 30%;
}

.@{kna-namespace}w33 {
	width: 33.3333%;
}

.@{kna-namespace}w40 {
	width: 40%;
}
```

**Comment by zouloux** [comment]
@raphaelgoetter j'ai 2 mains gauches, my bad ;)

**Comment by zouloux** [comment]
On dirait bien un problème côté grunt-contrib-less car rien d'illégal ou tourdu d'un point du vu syntaxique.

**Comment by posykrat** [comment]
Pour info j'avais la version 0.9.0 de grunt-contrib-less, je viens de passer à la 1.0.1, aucun changement.

**Comment by zouloux** [comment]
J'ai testé en forçant la variable depuis la config grunt 
```
less: {
                options: {
                    modifyVars: {
                        "kna-namespace" : ""
                    }
                }
            },
```
Toujours rien pas possible de compiler. On dirait vraiment que le compilateur less ignore les variables vides.
Je viens de me rendre compte qu'avec cette histoire de namespacing il n'y a plus d'autocompletion dans webstorm.

**Comment by dcaillibaud** [comment]
J'ai réglé un pb similaire (qui ressemble plutôt à #139) en dupliquant les sources less de knacss sans leur namespace dans un sous-dossier de mes fichiers less
```bash
for f in vendors/knacss/less/*.less; do sed -e 's/@{kna-namespace}//g' $f > styles/knacssSrc/$(basename $f); done
```
Et je peux maintenant faire du 
```css
/* copier les caractéristiques du style @{kna-namespace}bar dans mon style foo */
.foo { .bar(); }
```
Ça devrait régler également les pbs éventuels d'autocomplétion.

**Comment by raphaelgoetter** [comment]
Hello @posykrat : je viens aux nouvelles pour savoir si par hasard le problème se serait-il auto-résolu depuis le temps ? (mise à jour de grunt-contrib-less, ou changement de workflow de ton côté ?)

**Comment by posykrat** [comment]
Slt @raphaelgoetter, je te fais un retour plus précis asap mais le problème semble persister.

**Comment by posykrat** [comment]
**Petit test rapide avec cet environnement : **
- Npm v3.3.12
- Gulp v3.9.1
- gulp-concat v2.6.0
- gulp-less v3.0.5
- Windows 10
- Mise en place de Knacss en version Less via Bower

**gulpfile.js (à la racine) :**
```
var gulp = require('gulp');
var less = require('gulp-less');
var concat = require('gulp-concat');

gulp.task('less',function(){
    gulp.src([
        'bower_components/KNACSS/less/knacss.less',
        'src/*.*',
    ])
    .pipe(less())
    .pipe(concat('index.css'))
    .pipe(gulp.dest('deploy/'))
});
```

**Contenu de mon fichier main.less dans /src :**
```
@import (reference) '../bower_components/KNACSS/less/knacss.less';

body{
	border:1px solid red;
	.mod;
	.flex-container;
}

```
**Résultat de gulp less :**
```
[22:23:56] Using gulpfile F:\www\_lab\knacss\gulpfile.js
[22:23:56] Starting 'less'...
[22:23:56] Finished 'less' after 16 ms
Potentially unhandled rejection [2] .flex-container is undefined in file F:\www\_lab\knacss\src\main.less line no. 6
```
Si je renseigne le namespace de Knacss tout est ok.

**Comment by raphaelgoetter** [comment]
Alors là c'est vraiment bizarre car on a quasiment exactement le même workflow et chez nous c'est parfaitement OK.

Tu peux tenter avec ce dossier de projet-type ? http://goetter.fr/tmp/bretzel-master.zip

(faire un `npm run setup` pour installer les plugins nécessaires, les dépendances via Bower et lancer une première fois Gulp; puis compiler avec `gulp` pour les tâches de base, ou `gulp watch` pour surveiller les modifications.)

**Comment by magsout** [comment]
Je ne sais pas si c'est lié à Windows (je suis sous Mac), mais je n'arrive pas à reproduire le bug. 

@posykrat tente avec le project que propose @raphaelgoetter pour voir si ça vient d'une configuration particulière

**Comment by posykrat** [comment]
Hey,

Désolé pour la réponse tardive.

@raphaelgoetter le zip est corrompu.

J'ai testé via le plugin npm bretzel-start, pas de problème de namespace vide via la version Sass.
