### ISSUE TITLE
KNACSS 5

### ISSUE THREAD

**Issue by raphaelgoetter** [alsacreations/KNACSS#174]
## À faire / fait : 

- suppression du support IE8-IE9 (à partir de la version KNACSS 5.0, seul IE10 et supérieurs sont pris en charge)
- suppression du support LESS (à partir de la version KNACSS 5.0, seul le préprocesseur Sass est encore pris en charge pour des raisons de maintenabilité)
- mise à jour vers Normalize 4.1.1 : https://github.com/necolas/normalize.css/blob/4.1.1/CHANGELOG.md
- restructuration / renommage des fichiers avec préfixes `_config-`, `_layout-`, `_library-`, `_object-`, `_override-` (sur le principe global de ITCSS)
- ajout de la library include-media (http://include-media.com/) pour faciliter la gestion des media queries
- adaptation des variables de breakpoint pour les rendre compatibles avec include-media
- adaptation des fichiers gulpfile, package.json et bower.json
- grille "grillade" à présent en mobile first (par défaut 1 colonne sur "tiny", 2 colonnes sur "small", valeurs modifiables)
- préfixage des variables pour la grille. `$gutter` -> `$grid-gutter`, `$number` ->  `$grid-number`, `$left` -> `$grid-left` et `$right` -> `$grid-right`
- mise à jour de la documentation
- ajout de commentaires dans les grilles
- affichage la "table des matières" dans la feuille de styles non compressée

## À discuter : 

- adapter quelques nommages à ceux de Bootstrap ? Par exemple les responsive utilities tels que [`.hidden-sm-down`](http://hackerthemes.com/bootstrap-cheatsheet/#hidden-sm-down) (faire une liste). cf. http://v4-alpha.getbootstrap.com/migration/
- pousser la version 5 du repo sur npm

**Comment by f4bien** [comment]
Pour quand envisagerai-tu une version 5? As-tu une idée?

**Comment by raphaelgoetter** [comment]
@f4bien : c'est prévu pour le 1er avril 2016, on a encore un peu de temps :)

https://github.com/raphaelgoetter/KNACSS/milestones

**Comment by fgirardey** [comment]
Franchement je viens de regarder les slides de ITCSS et c'est excellent ce concept.

Moi je vote pour :+1:

**Comment by raphaelgoetter** [comment]
Il faut juste voir comment il est possible d'articuler un "framework" tel que KNACSS où le principe est que tes propres styles s'appliquent à la suite des styles du framework.
Je pense que ça risque d'être compliqué :/

**Comment by fgirardey** [comment]
Oui pour pouvoir glisser facilement ses components etc…

Il faudrait voir avec des experts LESS/Sass pour voir comment on pourrait charger nos styles au milieu et élaborer un bon workflow.

**Comment by raphaelgoetter** [comment]
même si c'est envisageable, cela risque d'être perturbant pour l'utilisateur unn peu novice : imagine que je souhaite créer des styles qui écrasent le framework, ... en fait ils vont eux-mêmes se faire écraser par la couche de Trumps et je risque de ne plus rien comprendre à ce qu'il m'arrive :/

**Comment by fgirardey** [comment]
Ah oui tu as raison… Après faut voir la cible de KNACSS, vu qu'il y a peu de design je pense (peut-être à tord) que c'est plutôt un outil utilisé par des développeurs front-end assez avancés.

Ça mérite reflexion en tout cas non ? :stuck_out_tongue_winking_eye:

**Comment by raphaelgoetter** [comment]
oui ça mérite réflexion :)

**Comment by f4bien** [comment]
Il serait peut-être intéressant de pousser un projet-exemple quant à la complétion des couches manquantes ITCSS? Une sorte de [Bootwatch](https://bootswatch.com/) pour Bootstrap mais avec des bonnes pratiques quand ce dernier, lui, ne fait qu'overrider l'existant.

**Comment by raphaelgoetter** [comment]
Je pense que c'est une bonne idée, mais concrètement je ne vois pas vraiment comment procéder pour l'instant.

**Comment by f4bien** [comment]
> mais concrètement je ne vois pas vraiment comment procéder pour l'instant.

Concernant? La mise en place d'un projet exemple ou comment découper proprement KNACSS pour faciliter le theming?

**Comment by raphaelgoetter** [comment]
un peu tout ça.

**Comment by f4bien** [comment]
L'idée que j'ai retenu c'est que ce ne soit pas dépendant de l'ordre des déclarations (ou des inclusions si utilisation de préprocesseurs), notamment si on utilise le css directement. En devenant de plus en plus spécifique on garantit une meilleure pondération des styles.  

Et quand bien même on aurait besoin de l'ordre d'inclusion, personnellement ma première action a été de m'approprier le fichier [knacss.less](https://github.com/raphaelgoetter/KNACSS/blob/master/less/knacss.less) pour retirer ta couche Wordpress donc ça ne serait pas incompatible avec le fonctionnement actuel de KNACSS. 

Je trouve le fonctionnement de [inuitcss](https://github.com/inuitcss/getting-started) top via dépendances bower (qui pourrait être via npm), mais ce n'est pas franchement à la portée de tous selon moi. 

Et pour le projet exemple dont je parlais, je peux facilement extrapoler un thème démo pour KNACSS V5 de mes projets en cours.

**Comment by raphaelgoetter** [comment]
> Et pour le projet exemple dont je parlais, je peux facilement extrapoler un thème démo pour KNACSS V5 de mes projets en cours.

Toi tu sais comment me parler !

**Comment by fgirardey** [comment]
Pour la découpe des fichiers et pour permettre d'inclure ses objects/components il faudrait voir pour créer des mixins qui permettrait de charger les fichiers à des instants précis.

Du genre un `add_component('./_gallery');` ou `add_object('./_gallery');` qui permettrait de garder l'architecture ITCSS.

Je sais pas si c'est possible mais bon

**Comment by stephendltg** [comment]
En somme l'idée de hook serait énorme et répondrait autant au developpeur qu'au novice. Le fait d'attaquer le framework a certain endroit serait le truc le plus révolutionnaire. On peut considérer deux type de hook les actions et les filtres idem a wordpress. Mais bon en css pur difficile, du coup knacss deviendrait full less ou full sass donc adieu aux novices qui veulent se lancer et je pense que c'est encore trop tôt pour l'avenir de knacss.

**Comment by raphaelgoetter** [comment]
@stephendltg 
> du coup knacss deviendrait full less ou full sass donc adieu aux novices qui veulent se lancer et je pense que c'est encore trop tôt pour l'avenir de knacss.

Tiens c'est tout à fait vrai ça. J'ai un peu honte de ne même pas avoir pensé aux usagers novices :/

**Comment by fgirardey** [comment]
Oui c'est sûr que ce sera compliqué pour les novices.

En tout cas sans preprocesseur je ne vois pas comment KNACSS pourrait passer en ITCSS 🤔

**Comment by stephendltg** [comment]
Knacss pour moi : c'est le wordpress du css. Il faut qu'il convienne autant aux développeurs qu'aux novices. C'est un outils professionnel à la portée de tous et c'est cela qui le différencie d'autre framework. Après ouvrir le principe du hook sur sass ou less permettrait de s'approprier le framework, de creer des plugins et du coup une communauté. Et une communauté est toujours un point fort pour la pérennité autant aux dev qu'aux novices. Mais bon je m'éloigne un peu du sujet mais voici ma vision de knacss.

**Comment by raphaelgoetter** [comment]
> Knacss pour moi : c'est le wordpress du css

Je ne sais pas comment le prendre, mais je crois que j'aime bien :)

**Comment by florianbouvot** [comment]
@raphaelgoetter le passage a une architecture type ITCSS est une excellente idée.

*Je pensais d'ailleurs que se serait le sujet de la conf de Harry Roberts à dotCSS 2014 (je t'en avais touché 2 mots :P ).*

En lissant les différents commentaires, je vois pas mal d'interrogations sur la mise en oeuvre et la gestion au quotidien... Si besoin je travail avec cette méthodologie depuis 2 ans donc hésites pas ;).

**Comment by f4bien** [comment]
@florianbouvot, pour ma part, je serai assez demandeur d'un exemple complet se basant sur cette méthode. Typiquement si tu déclares tes variables avant import et les overrides ensuite, sous quelle forme, où tu les inclus, où tu les stockes etc.

As-tu un repo à titre d'exemple pour un projet complet sous la main?

**Comment by florianbouvot** [comment]
@f4bien je peux te préparer un exemple complet. 

*Suivre ce type de méthodologie implique effectivement de comprendre certain point clés.*
Les variables sont gérer dans la partie settings, tu peux créer un (ou plusieurs fichiers) pour surcharger les variables du framework et ajouter les variables du projet (tout est une question d'organisation).

exemple 

style.scss
```scss
// Settings 
@import "settings.global"; // ton fichier de configuration overrides + tes variables
@import "settings.framework"; // fichier de configuration fournit par le framework

// Tools
...
```

settings.global
```sass
// Overrides framework
$framework-font-size:  1.2rem;
$framework-line-height: 1.4;

// Project variables
$color-primary: #8a2418;
```

settings.framework
```sass
// Framework defaults
$framework-font-size:  1rem !default;
$framework-line-height:  1.5 !default;
```

**Comment by Interned** [comment]
Hello,

La "table des matières" dans la feuille de styles non compressée pourrait-elle être à nouveau affichée ?

**Comment by raphaelgoetter** [comment]
@Interned pourquoi pas, oui
