### ISSUE TITLE
flex-item-double

### ISSUE THREAD

**Issue by michellomp** [alsacreations/KNACSS#180]
Bonjour j'utilise knaccs dans wordpress et pour avoir une grille de trois element : le 1 sidebar le content (qui est 2 fois plus que le sidebar ) et le 2 sidebar j'utilise donc la classe flex-item-double sur le div du content. Le probleme c'est que sur les petits ecrans le content prend la moitié de l'espace dispo.
 
    <div class="grid-4-small-1-tiny-1">
		
		<div >
			<?php dynamic_sidebar( 'sidebar-3' ); ?>
		</div>

		<div class="flex-item-double">
		     /*comment rendre ce contenu à 100% de largeur sur les petit ecran ?*/
	       </div>
               <div>
		     <?php dynamic_sidebar( 'sidebar-1' ); ?>
	        </div>
     </div>

**Comment by raphaelgoetter** [comment]
Hello,

C'est une erreur idiote, un simple faute de frappe : des `flex-item-double` notés `flexitem-double`.

Je corrige ça immédiatement.

**Comment by raphaelgoetter** [comment]
Cela devrait être corrigé (version 4.4.1)

**Comment by michellomp** [comment]
Merci
