### ISSUE TITLE
supprimer word-break sur les liens

### ISSUE THREAD

**Issue by raphaelgoetter** [alsacreations/KNACSS#183]
`word-break: break-all` est appliqué de base sur tous les liens en responsive.

C'est pratique en règle générale quand le contenu est une URL, mais cela coupe les mots lorsque le lien est du texte classique.

**Comment by PhilippeVay** [comment]
Est-ce qu'il y a encore `word-wrap: break-word` dans ce cas ou pas ?

Cas extrême : "oui mais si [l'URL fait 2000 caractères de long](http://stackoverflow.com/questions/417142/what-is-the-maximum-length-of-a-url-in-different-browsers)" :D

**Comment by raphaelgoetter** [comment]
Oui il y a.

En fait, l'ordre d'application par le navigateur est : 
1. word-break
2. hyphens
3. word-wrap

Les 3 sont (étaient) appliqués sur les liens.
