### ISSUE TITLE
Grillade : calc -.01px

### ISSUE THREAD

**Issue by eQRoeil** [alsacreations/KNACSS#184]
Hello Raphaël,

j'ai vu ```width: calc(100% * 1 / 4 - 2rem - .01px);``` dans [grillade.css](https://github.com/alsacreations/KNACSS/blob/master/css/grillade.css#L23) et je me suis demandé pourquoi tu ajoutais -.01px

je suppose qu'un (au moins) navigateur a un problème d'arrondi mais cela a éveillé ma curiosité&hellip;

**Comment by raphaelgoetter** [comment]
Bonjour @eQRoeil 

Tu as raison, c'est un choix bien obscur qui mériterait une explication en commentaires.

Le cheminement vient de ce bug d'arrondi sur IE : https://github.com/alsacreations/KNACSS/issues/133
