### ISSUE TITLE
Road to KNACSS V6

### ISSUE THREAD

**Issue by raphaelgoetter** [alsacreations/KNACSS#186]
## Idées en vrac / généralités...

- Améliorer la Convention de nommage des classes. Cf. https://github.com/alsacreations/KNACSS/issues/209 ?
- Remettre en question l'astuce du `font-size: 62.5%` ? Avis actuel : je penche pour garder. cf. https://blog.goetter.fr/2016/07/05/lastuce-du-font-size-62-5-oui-non-ou-ca-depend/
- Ajouter l'objet Autogrid : http://codepen.io/raphaelgoetter/pen/KMgBJd?editors=1100
- Ajouter l'objet Media : http://codepen.io/raphaelgoetter/pen/KMWWwj

- <del>Passer à une [grille en Grid Layout](http://blog.goetter.fr/2016/01/02/grid-layout-vers-la-grille-parfaite/) (IE10+ et le reste des navigateurs modernes ?) et une alternative en Flexbox ?</del>

## Grille

- Améliorer la grille actuelle. Cf. https://github.com/alsacreations/KNACSS/issues/207
- Laisser tomber la [bidouille du `.01px`](https://github.com/alsacreations/KNACSS/blob/master/less/_03-grids.less#L34) des grilles actuelles ? **EDIT :** non, c'est toujours buggué sur IE10-IE11 sans ce hack

## Breakpoints

- Revoir les valeurs des Breakpoints et les classes responsive. cf. https://github.com/alsacreations/KNACSS/issues/210
- Supprimer include-media (crée des bugs d'encodage, nécessite un temps d'apprentissage, et n'apporte pas grand chose au final), se baser sur un mixin ? https://github.com/zurb/foundation-sites/blob/develop/scss/util/_breakpoint.scss
- Corriger les intervalles ici : https://github.com/alsacreations/KNACSS/issues/208 (la règle doit être `(max-width: $BP) and (min-width: ($BP + 1))` )

## Positionnement

- Supprimer le positionnement tabulaire. `.row` et `.col` n'ont plus lieu d'être depuis Flexbox, peuvent entrer en conflit avec d'autres frameworks et ne font que parasiter KNACSS

## Modularisation

KNACSS doit pouvoir être utilisé par morceaux. Je dois pouvoir me contenter du reset + les grilles par exemple, ou bien juste les classes utilitaires, sans que ce soit compliqué.

Séparer dans un dossier spécifique : 

1- la config (variables de projet)
2- les vendor (normalize, include-media)
3- les library (base, print, misc, forms, tables)
4- les objects (media, autogrid, grid)
5- les utility classes (positionnement, rwd, helpers)
6- les grilles

## À piocher ailleurs

- https://github.com/jonathanlevaillant/atomic-builder (nommage, catégorisation, grille)
- idées aussi dans HTML5BP : https://github.com/h5bp/html5-boilerplate/blob/5.3.0/dist/css/main.css
- idées aussi dans http://fox-css.com/documents/

**Comment by PhilippeVay** [comment]
1. Quelles possibilités de Sass veux-tu utiliser que ne permet pas LESS ? Veux-tu vraiment complexifier le code de KNACSS au point que ce ne soit pas possible de le faire en LESS ? Une des raisons qui m'a fait choisir LESS et pas Sass en 2011 (après des tests approfondis de 0,5j :p ) est que ça reste forcément simple, pas de feature übercompliquée.

2. Est-ce qu'un framework peut simplifier l'usage de Grid Layout en proposant des classes toutes faites ou bien ce n'est pas plus long de le faire projet par projet avec les classes de son choix ?
Les `.flex-start` et `.flex-end` sont AMHA une super idée pour simplifier l'usage de Flexbox.
Mais vu que Grid Layout permet de faire ce qu'on veut en 2D et pas selon un simple axe (sans ou avec wrap comme Flexbox), la liberté est telle que... Et à chaque point de rupture, tu peux avoir un layout complètement différent.
Ce seraient AMHA plutôt les [templates](http://www.alsacreations.com/static/gabarits/) de @fvsch qui en profiteraient.

**Comment by raphaelgoetter** [comment]
> Quelles possibilités de Sass veux-tu utiliser que ne permet pas LESS ?
Pour commencer, les possibilités de boucles bien plus simples qu'en LESS (et bien pratiques quand on veut générer automatiquement des `.grid-2` ... `.grid-12` en évitant [ce qu'on fait actuellement en LESS](https://github.com/alsacreations/KNACSS/blob/master/less/_03-grids.less#L55)

> Veux-tu vraiment complexifier le code de KNACSS au point que ce ne soit pas possible de le faire en LESS ?
Le complexifier, carrément pas. Par contre faciliter certaines choses comme le point précédent, oui.

En fait, la raison globalement est encore plus simple : la plupart des usagers de pré-processeurs (autant intégrateurs que clients ou autres) sont plus habitués à Sass. Sans vouloir complexifier ni révolutionner notre process actuel, une migration me semble profitable à moyen-long terme.

> Est-ce qu'un framework peut simplifier l'usage de Grid Layout en proposant des classes toutes faites ou bien ce n'est pas plus long de le faire projet par projet avec les classes de son choix ?

Je ne sais pas si cela mériterait encore de s'appeler "framework" tant les possibilités natives de Grid Layout sont grandes.
Ceci dit, quelques classes bien choisies permettraient de faciliter les choses, et surtout d'apporter une sorte de consistance en nommage.

Dans cette démo, par exemple : http://codepen.io/raphaelgoetter/full/ZQLBxd/

On pourrait classer et automatiser pas mal de choses : 
- nombre d'éléments dans la grille
- premiers et derniers dans l'ordre
- row et col spanning
- gouttière ou non
- etc.

**Comment by ericemc3** [comment]
Bonjour,
je suis d'accord avec ces évolutions.

Et pourquoi ne pas laisser tomber la technique du 62.5% par la même occasion ?

**Comment by fgirardey** [comment]
Personnellement je préfère garder la technique du 62.5%.

Si le problème de conversion entre `rem` et `em` pose problème c'est généralement parce qu'on utilise pas les `rem` pour les bonnes raisons.

**Comment by ericemc3** [comment]
beaucoup en reviennent, et d'ailleurs l'excellent ouvrage (CSS3, pratique du design web) cosigné par Raphaël expose assez bien en quoi c'est une bidouille assez laide et une mauvaise pratique...

**Comment by fgirardey** [comment]
Ah oui je vois, moi je dis ça parce que le seul moment où ça a pu me poser problème c'était parce que je n'utilisais pas les bonnes unités pour les bonnes raisons. Après ça m'intéresse de savoir à quel niveau c'est une mauvaise pratique.

**Comment by raphaelgoetter** [comment]
Bon. En ce qui me concerne, je ne cautionne qu'*en partie* l'idée que ce soit une mauvaise pratique.

Voici ce que dit le livre CSS3 de Hugo : 

> Dans le but de simplifier les calculs de tailles de police, il est coutume de définir la taille de la
> police de la racine du document (l’élément html) à 62.5 % via la déclaration suivante :
> 
> ```
> /**
> * Taille par défaut du navigateur : 16 px
> * 16 × 62.5% = 10 px
> */
> html {
> font-size: 62.5%;
> }
> ```
> 
> En effet, tous les navigateurs ont par défaut une taille de police de 16 pixels. Or 16 × 62.5
> vaut 10, ce qui rend tous les calculs autour de l’unité rem extrêmement évidents. Besoin de
> l’équivalent de 16 pixels ? Facile, c’est 1.6rem.
> 
> Malheureusement, je me dois de faire l’avocat du diable et de vous intimer de cesser cette
> mauvaise pratique. Effectivement, cette astuce transforme des calculs pénibles en simples
> opérations mentales, mais elle présente aussi des inconvénients.
> En effet, elle va nécessiter de redéfinir la taille de la police de tous les conteneurs textuels, tels
> que p, li, les titres, et bien d’autres encore. Les calculs sont donc plus simples, mais en même
> temps plus nombreux !
> En définissant la taille de police de la racine du document à la taille de texte désirée, généralement
> entre 12 et 20 pixels, on s’abstient de devoir redéclarer la font-size sur tous les éléments !

Mais ce que ne dit pas le livre (et tous les articles contre cette pratique), est qu'il n'est pas du tout nécessaire de devoir redéfinir la taille de tous les éléments textuels... il suffit d'ajouter une règle très simple : 

```
body {
  font-size: 1.4em; /* la taille de base pour tous les éléments sera un équivalent de 14px */
}
```

C'est aussi simple que cela, et c'est ce que fait déjà KNACSS depuis très longtemps.

En bref, avec cette technique : 
- on conserve une taille de base fluide de 1.4em/px pour tous les éléments (= on ne casse rien du tout)
- on bénéficie d'une compréhension et d'une maintenance de code ultra-simplifiée dès lors qu'on utilise des rem sans pré-processeurs. Parce qu'un jour on se passera de pré-processeurs ;)

**Comment by ericemc3** [comment]
et merci pour ces explications fort détaillées ! Cela n'alourdit pas le code en effet autant que certains le prétendent. Mais les "plus" me paraissent insuffisants eu égard aux inconvénients d'une pratique non standard, et qui semble en perte de vitesse

**Comment by fgirardey** [comment]
Mais quels sont les inconvénients du coup @ericemc3 ? Comme le dit @raphaelgoetter une simple règle sur le body évite d'alourdir le code. Tu vois d'autres soucis potentiels ?

**Comment by ericemc3** [comment]
ce qui me gêne juste c'est la compatibilité entre différents projets. Pour certains je compte utiliser Knacss, pour d'autres je m'appuie sur d'autres librairies/frameworks, et jongler dans les media queries, d'un projet à l'autre, entre différentes significations des unités me trouble. Je m'étais dit au début, ce n'est pas grave, tout le monde va passer à cette règle du 62.5 %, qui devient un standard. Mais j'ai l’impression que c'est plutôt l'inverse. Maintenant, ce n'est pas dramatique, et Knacss est un superbe outil

**Comment by fgirardey** [comment]
C'est pas faux ce que tu dis @ericemc3… à choisir sur d'autres projets je préfère également 1rem = 16px, faudrait faire un sondage 😇

**Comment by fvsch** [comment]
Perso je préfère:

```css
html {
  /* With default browser settings, 1rem = 20px */
  font-size: 125%;
}
body {
  /* For instance, if we want to default to 15px */
  font-size: .75rem;
}
```
Okay ça rajoute une division par 2, ce qui peut perturber un peu, mais c’est pas Maths Sup.
Et c’est vachement courant d’avoir des écarts de 20px (ou multiples de 20) dans un design.

Mais bon c’est pas indispensable.

Ah oui et un problème qu’avait la technique du `62.5%` à une époque c’est que certains navigateurs avaient des options pour fixer une taille de texte minimum, et si on la fixait à `12px` par exemple le `font-size` de l’élément `html` restait à 12px, puis on demandait par exemple du `1.5em` pour obtenir du 15px mais on obtenait donc du 18px.

**Comment by raphaelgoetter** [comment]
Bonjour et merci à tous pour vos arguments et explications.

Dans notre équipe, la règle du `62.5%` est toujours largement et unanimement appréciée : aucun bug connu nulle part, une maintenance et une lecture du code simplissime. Bref, on ne va certainement pas modifier ce point à court terme dans KNACSS.

En tout cas, on préfère toujours cette règle plutôt que celle choisie par Bootstrap dont même la toute dernière version [impose encore du pixel](http://getbootstrap.com/css/#type-body-copy) : 

> Bootstrap's global default font-size is 14px, with a line-height of 1.428. 

(beurk)

**Comment by ericemc3** [comment]
Bonjour,

cela me parait en effet sensé, si c'est simple et que ça marche, oublions les débats métaphysiques !

Merci pour ce débat fort intéressant.

**Comment by nico3333fr** [comment]
Y a un léger bug sous IE9-11 avec le 62.5%, l'arrondi donne 9px et des poussières : cela se fixe avec : 
font-size: calc(1em * 0.625);

Juste au cas où ;)

**Comment by raphaelgoetter** [comment]
@nico3333fr : oui c'est en place depuis un petit bout de temps normalement : https://github.com/alsacreations/KNACSS/blob/master/sass/_01b-base.scss#L43 ;)

**Comment by nico3333fr** [comment]
@raphaelgoetter autant pour moi, j'ai regardé la version CSS un peu trop vite :)
