### ISSUE TITLE
KNACSS 4.4.5 / select {overflow: visible;} affiche toutes les options des éléments <select>

### ISSUE THREAD

**Issue by Levure** [alsacreations/KNACSS#190]
Bonjour !

En testant KNACSS 4.4.5 avant mise en production, je me rends compte que **toutes** les options des éléments <select size="3">s'affichent alors qu'on ne devrait en voir que 3. (les options suivantes s'affichent d'ailleurs en dehors de leur <select> parent)

Un exemple est visible sur cette URL : http://www.capharnaum.be/knacss_20160407/index.php

Ce problème me semble être causé par le bloc suivant :

```css
button, hr, input, select {
    overflow: visible;
 }
```

Aurais-je loupé une subtilité ?

D'avance merci ! :-)

**Comment by raphaelgoetter** [comment]
Ah oui c'est intéressant.

Tu as raison sur l'origine du problème. Mais cela ne vient pas de KNACSS mais du reset intégré dans KNACSS, c'est à dire Normalize : https://github.com/necolas/normalize.css/issues

Normalize est très célèbre et mondialement utilisé sur d'énormes sites web? C'est assez bizarre qu'une telle erreur puisse passer.

Je pense que le mieux serait de les informer en créant une issue directement chez eux : https://github.com/necolas/normalize.css/issues

En attendant, tu peux écraser cette valeur en remettant les valeurs par défaut : 

```
select {
    overflow-x: hidden;
    overflow-y: scroll;
}
```

**Comment by Levure** [comment]
De fait, une issue y est d'ailleurs déjà créée : https://github.com/necolas/normalize.css/issues/562

**Comment by raphaelgoetter** [comment]
Bien vu :)

**Comment by PhilippeVay** [comment]
Le fix devrait être https://github.com/necolas/normalize.css/compare/fix/562
