### ISSUE TITLE
v5 : _override-reponsive.scss : erreur de code ou de doc

### ISSUE THREAD

**Issue by davidb583** [alsacreations/KNACSS#194]
Bonjour,

   Je ne comprends pas la déclaration suivante dans _override-responsive.scss : 

```
@include media('>=small-screen', '<medium-screen') {

  /* quick reset in small resolution and less */
  .#{$kna-namespace}w600p,
  .#{$kna-namespace}w700p,
  .#{$kna-namespace}w800p,
  .#{$kna-namespace}w960p,
  .#{$kna-namespace}mw960p {
    width: auto;
    float: none;
  }
}
```

soit il y a besoin d'un quick reset sur les toutes petites résolutions, mais auquel cas la media query est fausse car elle ne fait l'adaptation que entre small et medium screen.

soit il y a besoin d'une configuration "spéciale" pour les largeur entre small et medium, mais je ne vois pas très bien pourquoi.

en attendant j'ai supprimé cette portion dans mon code, mais si il y a une correction à faire je veux bien faire la PR

**Comment by raphaelgoetter** [comment]
Bonjour,

Oui, il est actuellement nécessaire d'écraser les largeurs dans l'intervalle "small - medium".

Le principe est d'ailleurs également appliqué sur petits écrans : 

```
@include media('<small-screen') {

  .#{$kna-namespace}w300p,
  .#{$kna-namespace}w400p,
  .#{$kna-namespace}w500p {
    width: auto;
    float: none;
  }
}
```

Par contre, ton intervention m'a fait penser qu'on pourrait sans-doute faciliter les choses : 
https://github.com/alsacreations/KNACSS/issues/195
