### ISSUE TITLE
Helpers en version mobile-first ?

### ISSUE THREAD

**Issue by raphaelgoetter** [alsacreations/KNACSS#195]
Aujourd'hui, les helpers de largeurs fonctionnent ainsi (en résumé) :
```
.w50p {
  width: 50px;
}
.w100p {
  width: 100px;
}
.w150p {
  width: 150px;
}
.w200p {
  width: 200px;
}
.w300p {
  width: 300px;
}
.w400p {
  width: 400px;
}
.w500p {
  width: 500px;
}
.w600p {
  width: 600px;
}
.w700p {
  width: 700px;
}
.w800p {
  width: 800px;
  }
.w960p {
  width: 960px;
}
```

Et la feuille de style responsive les écrase au fur et à mesure : 

```
@include media('>=small-screen', '<medium-screen') {

  /* quick reset in small resolution and less */
  .#{$kna-namespace}w600p,
  .#{$kna-namespace}w700p,
  .#{$kna-namespace}w800p,
  .#{$kna-namespace}w960p,
  .#{$kna-namespace}mw960p {
    width: auto;
    float: none;
  }
}

@include media('<small-screen') {

  .#{$kna-namespace}w300p,
  .#{$kna-namespace}w400p,
  .#{$kna-namespace}w500p {
    width: auto;
    float: none;
  }
}
```

J'ai très envie de rendre le fonctionnement bien plus simple avec une méthode "mobile-first" : 

```
.w50p {
  width: 50px;
}

.w100p {
  width: 100px;
}

.w150p {
  width: 150px;
}

.w200p {
  width: 200px;
}

.w300p {
  width: 300px;
}

@include media(‘>tiny-screen') {

  .w400p {
    width: 400px;
  }

  .w500p {
    width: 500px;
  }

  .w600p {
    width: 600px;
  }

}

@include media(‘>small-screen') {

  .w700p {
    width: 700px;
  }

  .w800p {
    width: 800px;
  }

  .w960p {
    width: 960px;
  }

}
```

Voyez-vous un gros inconvénient à passer à cette seconde méthode ?

**Comment by raphaelgoetter** [comment]
Tant qu'à faire (sur une suggestion de @PhilippeVay ) plutôt que de prendre le risque de mélanger des valeurs en dur (`600p`) et des mots-clés (`small-screen`) pouvant être modifiables, autant utiliser des Media Queries avec des valeurs en dur également  : 

`@include media(‘>small-screen')` --> `@include media(‘>640px')`

**Comment by PhilippeVay** [comment]
Je signalais qu'il pouvait y avoir un problème pour ceux modifiant les valeurs des _breakpoints_ des MQ mais j'étais d'avis de laisser comme dans ta 1ère suggestion. :p À la relecture (ou avec le ventre plein) ta dernière proposition est plus mieux : peu importe les valeurs souhaitées par le développeur, ces classes sont à rendre inopérantes au-dessus de valeurs bien fixes donc :+1:
