### ISSUE TITLE
Supprimer les classes de largeurs en pixel ?

### ISSUE THREAD

**Issue by raphaelgoetter** [alsacreations/KNACSS#196]
Les classes "helpers" de largeurs en pixels me semblent de moins en moins appropriées à un framework.

 ````
.#{$kna-namespace}w150p {
  width: 150px;
}
```

Je pense qu'on pourrait les supprimer et ne conserver que les classes exprimées en pourcentages.

**Comment by PhilippeVay** [comment]
> raphaelgoetter added this to the **KNACSS 5.0.2** milestone 3 days ago

C'est une modification _majeure_ qui va casser les projets de pas mal d'utilisateurs :dizzy_face:  (je parierais quelques _kopecks_ sur les champs de formulaire)
ça devrait donc faire l'objet d'un changement _majeur_ de version ([semver](http://semver.org)) c'est-à-dire `v6.0.0` (et _nope_ le fait que tu aies sorti la v5 il y a 6 jours n'a aucune espèce d'importance :no_good: )
