### ISSUE TITLE
Koala + knacss

### ISSUE THREAD

**Issue by Mthweb** [alsacreations/KNACSS#197]
Bonjour,
En utilisant knacss et koala j'ai une erreur : 
Error: Invalid US-ASCII character "\xE2"
        on line 253 of /Users/mth/dev/portfolio/sass/_include-media/_include-media.scss
        from line 28 of /Users/mth/dev/portfolio/sass/knacss.scss
  Use --trace for backtrace.

la ligne en question : 
`@each $operator in ('>=', '>', '<=', '<', '≥', '≤') {`

**Comment by raphaelgoetter** [comment]
C'est très curieux en effet, d'autant plus que la ligne en question ne semble pas problématique : 
https://github.com/alsacreations/KNACSS/blob/master/sass/_include-media/_include-media.scss#L253

Le fichier en question n'est pas produit par KNACSS, c'est *include_media* qui est récupéré. Il faudrait peut-être voir directement avec les auteurs de include_media, à savoir @eduardoboucas et @HugoGiraudel sur le repo suivant : https://github.com/eduardoboucas/include-media

Bonne chance !

**Comment by PhilippeVay** [comment]
Bonjour,
Le compilateur Sass de koala est - [en y cherchant "Sass"](https://github.com/oklai/koala/search?utf8=%E2%9C%93&q=sass) - ruby-sass alors que nous utilisons libsass et j'ai d'abord pensé que `\xE2` était le caractère `≥` MAIS après avoir recherché "[character xe2](https://duckduckgo.com/?q=character+xe2&t=ffsb)", je crois que ce sont 2 fausses pistes...
Déjà `\xE2` c'est `â` d'après [Wikipedia](https://en.wikipedia.org/wiki/%C3%82#Character_mappings) mais ensuite pas mal de problèmes qui remontent sont liés à Python, Bourbon, des éditeurs, etc [dans INUIT](https://github.com/csswizardry/inuit.css/issues/270) ou [dans HAML](https://github.com/haml/haml/issues/269) et la 1ère solution évoquée est d'ajouter `@charset "UTF-8";` au début de chaque fichier.
C'est déjà dans le cas dans _include-media_ mais pas dans `knacss.scss` qui l'importe. Pourrais-tu réessayer en rajoutant cette directive `@charset "UTF-8";` avant le 1er import stp ?
Sinon il faudrait que tu enlèves dans `include-media` toutes les occurences de `≥` et `≤` et que tu réessaye : ça permettra d'être _certain_ que ces caractères sont bien la source du problème à résoudre :)

**Comment by PhilippeVay** [comment]
_Related_ [include-media closed issue #84 "Charset error, invalid character"](https://github.com/eduardoboucas/include-media/issues/84) et le 1er commentaire de prisis
