### ISSUE TITLE
Fix SVG in <img>

### ISSUE THREAD

**Issue by Alysko** [alsacreations/KNACSS#199]
Bonjour,

Je ne sais pas si ça a sa place ici, mais je viens de rencontrer un problème avec une grande partie de mes SVG utilisés dans l'élément <img> sur IE11 : les proportions étaient bonnes mais pas la taille, voire une taille et une proportion exacte mais un conteneur carré pour une image qui ne l'est pas, laissant de l'espace en haut et en bas du SVG.

La solution a été de spécifier un width: 100%.

J'ai utilisé le hack CSS (puisque IE>9 ne gère plus les commentaires conditionnels) de [ce gist](https://gist.github.com/ricardozea/5549389) et ça fonctionne correctement.

**Comment by raphaelgoetter** [comment]
Bah, c'est osé d'imposer un `width: 100%` à tous les SVG de base, ça dépasse un peu la portée d'un "framework", c'est à faire au cas par cas.

Sinon, pour les hacks, je te conseille ce super site de @HugoGiraudel : http://browserhacks.com/

**Comment by Alysko** [comment]
Tu l'imposes uniquement à IE. De toutes façons, si tu ne le fais pas, ça déconne et quand tu as besoin de spécifier un width, tu le fais généralement avec un sélecteur de plus gros poids, non ?

Super le site de Hugo, merci !

**Comment by raphaelgoetter** [comment]
Hello,

Je suis en train de travailler sur cette issue. Tu peux me dire ce que tu as fait finalement ?

Quelque chose comme ça ?

```
.hackIE11 svg {width: 100%;}
```

**Comment by Alysko** [comment]
Oui, j'ai fait 

`@media screen and (-ms-high-contrast: active), (-ms-high-contrast: none) {
  img[src$=".svg"] {
    width: 100%;
  }
}`

Parce qu'il manque un morceau dans mon message de départ :

> problème avec une grande partie de mes SVG utilisés dans l'élément **<img>** sur IE11

**Comment by Efflamm** [comment]
Bonjour,

Finalement vous avez intégré ce morceau de code dans knacss.css
A l'inverse de @Alysko je n'ai pas de problème avec EI 11 et les svg. Le seul soucis c'est qu'ils sont tous énorme maintenant.  En spécifiant une width directement sur chaque`<img>` le problème est resolue pour la plupart des navigateurs mais IE11 leur met toujours une width de 100%. J'ai du supprimer ce bout de code a la main du coup. Je trouve aussi que 

> c'est osé d'imposer un width: 100% à tous les SVG de base

et qu'il vaudrait mettre ce bout de code en option a ajouter depuis le site de knacss si l'on rencontre des problèmes.

**Comment by raphaelgoetter** [comment]
@Efflamm Tu as entièrement raison, je vais modifier ça immédiatement.
