### ISSUE TITLE
Prévoir des helpers responsive

### ISSUE THREAD

**Issue by raphaelgoetter** [alsacreations/KNACSS#200]
Ex.

```
.large-pal .medium-pam .small-pas
```

(pour l'instant, seul `-pan` est prévu)

**Comment by bdavidxyz** [comment]
On peut étendre aux margins ? seul le -man est prévu également, pour l'instant

**Comment by bdavidxyz** [comment]
Autre remarque : on peut imaginer plusieurs combinaisons, comme vouloir des petits paddings sur écran large, et des grands paddings sur petits écran ? Ou bien sont-ce des cas exotiques ?

**Comment by fgirardey** [comment]
@bdavidxyz Je suis moyennement d'accord sur ce genre de changements car KNACSS est un framework de structure, pas de design. Enfin c'est l'utilisation que j'en ai donc ça m'embêterait un tel comportement 😅

**Comment by bdavidxyz** [comment]
I see. PR en cours #201

**Comment by raphaelgoetter** [comment]
Après longue réflexion, je suis finalement de l'avis de @fgirardey et ne vais pas poursuivre dans les ajouts graphiques.
