### ISSUE TITLE
Symfony2, erreur de compilation : Invalid US-ASCII character "\xE2"

### ISSUE THREAD

**Issue by raphaelriehl** [alsacreations/KNACSS#203]
Bonjour,

En compilant knacss avec assetic dans un environnement symfony 2.8.
J'ai rencontré l'erreur suivante : Invalid US-ASCII character "\xE2" sur le fichier `_include-media/_include-media.scss` et `_library-styling.scss`.

Les solutions en ligne indiquaient de spécifier le charset dès la première ligne du document, hors c'était déjà le cas pour "_include-media/_include-media.scss".

Pour solutionner ce problème, il faut remplacer
`@charset 'UTF-8';`
par
`@charset "UTF-8";`
Et ajouter cette ligne dans les fichiers suivants qui posent problème.

En espérant que cela soit utile à d'autres. :)

**Comment by raphaelgoetter** [comment]
Bonjour @raphaelriehl et merci pour l'info.

Je peux le modifier à la main dans KNACSS mais ce ne sera pas tellement utile car le fichier sera écrasé dès qu'une nouvelle version de include_media sortira.

Te serait-il possible d'ouvrir une issue directement sur leur repo ? 
Le lien direct : https://github.com/eduardoboucas/include-media/issues

Merci d'avance ;)

**Comment by PhilippeVay** [comment]
2e fois qu'un problème UTF-8 revient, cf. #197 :(

**Comment by raphaelriehl** [comment]
Du coup, j'ai répondu sur une issue déjà ouverte sur leur repo.

Par contre, est-ce que le charset avec les double quotes pourrait être ajouté dans le fichier `_library-styling.scss` de knacss ? Voir même dans tous les fichiers scss de knacss ?

**Comment by raphaelgoetter** [comment]
En fait, comme dit : 

> Je peux le modifier à la main dans KNACSS mais ce ne sera pas tellement utile car le fichier sera écrasé dès qu'une nouvelle version de include_media sortira. :( 

Et pour ce qui est du charset sur tous les fichiers, je ne suis pas super fan a priori : c'est le boulot du serveur qui doit être correctement configuré pour cela. Je ne pense pas qu'un charset puisse écraser une mauvaise config serveur :/

**Comment by raphaelriehl** [comment]
Je ne parlais que des fichiers propres à Knacss, pas include_media. :)
Pour include_media je leur ai fait une demande de modification.

> Et pour ce qui est du charset sur tous les fichiers, je ne suis pas super fan a priori : c'est le boulot du serveur qui doit être correctement configuré pour cela.

Je comprend. Je plaide coupable pour ne pas avoir cherché à configurer proprement mon serveur. :D
