### ISSUE TITLE
Grille responsive : problème de rupture sur fieldsets

### ISSUE THREAD

**Issue by ylegrand** [alsacreations/KNACSS#208]
Bonjour à tous,

J'utilise pour la première fois KNACSS, et j'observe un comportement étrange lorsque je souhaite disposer des fieldsets en colonnes sur une grille responsive.

Ma structure est la suivante :
```
<div class="grid-3-small-1">
    <fieldset>[...]</fieldset>
    <fieldset>[...]</fieldset>
    <fieldset>[...]</fieldset>
    <fieldset>[...]</fieldset>
</div>
```

Le souci porte sur la rupture "small". Le comportement est le suivant :

- A partir d'une largeur **>= 641px**, j'ai bien mes  **3 colonnes** (https://www.dropbox.com/home/Public?preview=20160708141033.PNG)
- Lorsque la lageur est **exactement 640px**, je retombe bien sur **une seule colonne** (https://www.dropbox.com/home/Public?preview=20160708141322.PNG)
- A partir d'une largeur **<=639px**, mes **3 colonnes** sont de retour -_- (https://www.dropbox.com/home/Public?preview=20160708141531.PNG)

La règle CSS qui prend le pas est la suivante (ligne 1595 du la version 5.0.1 de knacss.css) 
```
@media (max-width: 639px)
.mod, .col, fieldset {
    display: block !important;
    float: none !important;
    clear: none !important;
    width: auto !important;
    margin-left: 0 !important;
    margin-right: 0 !important;
    border: 0;
}
```

Est-ce un comportement normal ? M'y prends-je correctement ?
Merci par avance pour l'attention que vous porterez à ce problème.

**Comment by raphaelgoetter** [comment]
C'est carrément un bug en effet. Je regarde ça de plus près.
