### ISSUE TITLE
KNACSS v6 : conventions de breakpoints

### ISSUE THREAD

**Issue by raphaelgoetter** [alsacreations/KNACSS#210]
Le nombre de variables de breakpoints [est actuellement de 10](https://github.com/alsacreations/KNACSS/blob/master/sass/_config-variables.scss#L48), sur KNACSS v5.

Il est prévu d'en supprimer un certain nombre et de les redéfinir.

Pourquoi ?

1. Parce que cela fait beaucoup. Cela peut se justifier sur un ou deux projets (et dans ce cas, rien n'empêche d'en ajouter soi même), mais pas en règle générale
2. Parce qu'en toute logique, les valeurs des BP varient selon chaque projet (définies selon le design et non selon des valeurs pré-établies), donc autant ne pas inciter à employer des valeurs pré-établies
3. Parce que la plupart des autres frameworks que j'ai survolé ne proposent pas autant de BP
4. Parce qu'un grand nombre de variables est source de confusion et d'oublis

## Les valeurs actuelles (™) (hihi)

```
$tiny-screen       : 320px; 
$tiny-plus-screen  : 480px;
$small-screen      : 640px;
$small-plus-screen : 768px;
$medium-screen     : 960px;
$medium-plus-screen: 1024px;
$large-screen      : 1280px;
$large-plus-screen : 1440px;
$extra-large-screen: 1600px;
$ultra-large-screen: 1920px;
```

## Les valeurs prévues pour KNACSS v6

Les valeurs suivantes sont issues du framework [Bootstrap 4](http://v4-alpha.getbootstrap.com/layout/responsive-utilities/) (même si le nommage des variables est différent) : 

```
// Warning : you should use your own values, regardless of the devices
$tiny: 544px; // or 'em' if you prefer, of course
$small: 768px;
$medium: 1024px;
$large: 1200px;
$extra-large: 1440px; // KNACSS add-on
```

Illustration :
![offset](https://raw.githubusercontent.com/raphaelgoetter/KNACSS/master/doc/illust/breakpoints.png)

### Choix des valeurs de breakpoints

1. Choisir principalement des valeurs de breakpoints selon votre design, pas par rapport à des devices (se servir des variables de breakpoints fournies si l'on ne peut pas se baser sur son design)
2. En plus de vos propres valeurs, il est possible d'employer : 
  - les variables fournies (`$tiny`, `$small`, `$medium`, `$large`), 
  - mais aussi des alias qui représentent des intervalles et que l'on utilise sous forme de mixins: (`mobile`, `portrait`, `landscape`, `desktop`)
3. Éviter de multiplier les valeurs. Un maximum de 5 ou 6 breakpoints devrait suffire dans la grande majorité des projets
4. Pour éviter les intervalles qui se chevauchent, ou des Media Queries trop variés, adopter une convention pour définir la valeur d’un Breakpoint : `(max-width: $BP) and (min-width: ($BP + 1))`

Exemple :

Non, pas bien :
```
@media (min-width: 768px) {...}
@media (max-width: 767px) {...}
```

Oui, bien :
```
@media (min-width: 769px) {...}
@media (max-width: 768px) {...}
@media (max-width: $small-screen) {...}
@media (min-width: $small-screen + 1) and (max-width: $large-screen) {...}
```

## Mixins "Alias"

En addition aux variables, des mixins de breakpoints "utilitaires" (des "alias" des valeurs précédentes) liées aux types de devices (forcément indicatifs, mais simples à retenir) sont prévues : 

**NOTE : je commence à avoir du mal avec les « large, medium, small » : en pratique, je ne sais jamais à quoi ça correspond et je dois systématiquement aller vérifier dans le fichier de variables. 
Au final, je me dis qu’un « mobile, tablet, desktop », même purement indicatif est bien plus parlant**

```
// Additionnal "utility" breakpoints aliases
@function breakpoint($bp) {
  @if $bp == 'mobile' {
    @return '(max-width: #{$tiny})';
  }
  @else if $bp == 'portrait' {
    @return '(min-width: #{$tiny + 1}) and (max-width: #{$small})';
  }
  @else if $bp == 'landscape' {
    @return '(min-width: #{$small + 1}) and (max-width: #{$medium})';
  }
  @else if $bp == 'desktop' {
    @return '(min-width: #{$medium + 1})';
  }
  @else if $bp == 'portrait-down' {
    @return '(max-width: #{$small})';
  }
  @else if $bp == 'portrait-up' {
    @return '(min-width: #{$tiny + 1})';
  }
  @else if $bp == 'landscape-down' {
    @return '(max-width: #{$medium})';
  }
  @else if $bp == 'landscape-up' {
    @return '(min-width: #{$small + 1})';
  }
  @else if $bp == 'retina' {
    @return '(-webkit-min-device-pixel-ratio: 2), (min-resolution: 192dpi), (min-resolution: 2dppx)';
  }
}

@mixin respond-to($value) {
  $string: breakpoint($value);
  @media screen and #{$string} {
    @content;
  }
}
```

Exemple d'usage : 

```
// styles
.when-portrait-up {
  @include respond-to("portrait-up") {
    background: green;
    color: #fff;
  }
}
.is-hidden-mobile {
  @include respond-to("mobile") {
    display: none;
  }
}
```

Voir le CodePen : http://codepen.io/raphaelgoetter/pen/EyRwAp/?editors=1100

Le Sassmeister : http://www.sassmeister.com/gist/309e39237e38655156dec98fcce8e0a2

**Comment by nico3333fr** [comment]
Je suis assez dans cette esprit sur Röcssti : site simple => 3 voir 4 breakpoints principaux, et on essaie d'harmoniser. 10 breakpoints majeurs (je dis bien majeurs !), c'est énorme :o je ne crois jamais avoir eu besoin d'autant, même sur du mobile-first.
(bien sûr en em chez Röcssti, mais pas de troll sur ce sujet, j'ai épuisé mon quota énergie à troll hier)

En général : un "tablette" (qui oscille en général entre 768 et 960), un "mobile" (qui tourne autour de 6/700) et un tout petit écran (qui oscille entre 500 et moins). Évidemment, je les customise à chaque projet, selon les contenus. 

+1 pour l'abandon de large/medium/small, je n'ai jamais été fan de cette nomenclature (même si elle est loin d'être idiote). D'autant plus que si on zoome, on peut avoir le layout medium/small sur un énorme écran "large". Je préfère parler de présentation mobile/tablette/etc.

**Comment by nhoizey** [comment]
@nico3333fr pourquoi « même sur du mobile-first » ? Pourquoi en faudrait-il plus en Mobile First ?!

C'est quoi, vos mobile à 6/700 ? Mon iPhone 6s a 375px de large… o_O

Pour la dénomination, je préfère quand même S, M, L à mobile, tablette, desktop, qui sont encore moins « vrais ».

**Comment by ryuran** [comment]
Je préfère aussi S, M, L à mobile, tablette, desktop.

mobile, tablette, desktop : ce sont des cibles que l'ont peut située entre nos breakpoints.

Par exemple on peut dire que toutes les cibles de type mobile en portrait se situent sous le breakpoint S.

Ça demande un peu d'habitude mais rien de mieux qu'une illustration sous forme de frise avec ces points à partager à toute l'équipe.

**Comment by raphaelgoetter** [comment]
@ryuran en fait c'est justement l'idée prévue : "mobile" n'est pas un breakpoint mais un alias pour "plus petit que $tiny-screen".
C'est ce que tu proposes, non ?

**Comment by DirtyF** [comment]
Peu importe les valeurs par défaut, il y a tellement de tailles d'écrans différentes, que de toute façon y'a de grandes chances de devoir les changer.

Je ne connais pas KNACSS, mais du coup ce que j'attend d'un framework c'est : 

* Pouvoir redéfinir les variables des breakpoints par défaut - en em bien sur ;)
* Pouvoir facilement ajouter des breakpoints personnalisés en fonction de ses contenus (Neat propose un mixin pour ça : http://thoughtbot.github.io/neat-docs/latest/#new-breakpoint)
* Proposer un mixin pour définir simplement une media query (http://thoughtbot.github.io/neat-docs/latest/#media)

**Comment by raphaelgoetter** [comment]
Merci à tous pour vos retours et ce premier aperçu du travail à fournir ;)

**Comment by ryuran** [comment]
J'utilise sass-mq avec une list de breakpoint qui varie selon les projets.
Je documentes les résolutions cible et les media queries à utiliser ou pas
En mobil first on autorisera que des `mq($from: X)` où X est le breakpoint.
L'important est d'avoir une frise ou un repère pour que le testeur sache dans quelle media queries il tombe et ce quelque soit le device.

+1 pour pouvoir redefinir la liste de breakpoint
+1 pour une liste de "main breakpoints" et une liste "tweak points"

-1 pour utiliser le mot "screen" quand on parle du viewport (on peut avoir un tout petit viewport dans un très grand écran)

**Comment by mchandelier** [comment]
J'utilise la mixin respond-to avec 5 breakpoints principaux et 2 qui englobent plusieurs tailles d'écrans lorque l'on veut des styles identiques du mobile jusqu'à desktop par exemple.
Je me sers principalement de 3 breakpoints (mobile jusqu'à 415px, portrait jusqu'à 768px, landscape jusqu'à 1024px) et vais certainement supprimer les 2 autres qui sont large, jusqu'à 1280px et wide, à partir de 1280px car ils ne servent jamais.

**Comment by raphaelgoetter** [comment]
Merci, je continue à avancer sur toutes les pistes.
