### ISSUE TITLE
Grid uneven responsive ?

### ISSUE THREAD

**Issue by Joel-Mercier** [alsacreations/KNACSS#212]
Bonjour et tout d'abord merci pour KNACSS je l'utilise sur tous mes projets ! 👍 

J'aime l'idée des grilles inégales que propose KNACSS cependant je me demandais comment il est possible de gérer le responsive d'une telle grille car j'aimerais un layout en grid-1-2 sur les écrans medium et plus, et en une seule colonne en dessous (small) Lorsque j'essaye `<div class="grid-1-2-small-1></div>` ou encore `<div class="grid-1-2-small-1-1></div>` je n'obtiens toujours qu'une colonne quelle que soit la taille de la fenêtre. KNACSS gère t'il ce cas là ?

Merci d'avance pour vos réponses et bonne journée ! :)

**Comment by raphaelgoetter** [comment]
Bonjour Joel-Mercier et merci pour ce beau compliment.

Il se trouve que, justement, parmi les fonctionnalités les moins (ou les plus mal) utilisées de KNACSS figure les "uneven grids" : la plupart du temps les gens s'en servent non pas pour des grilles, mais uniquement pour positionner 2 blocs côte à côte, ce qui n'est pas du tout leur but.

La mauvaise nouvelle est donc que les "uneven grids" vont disparaître dans la prochaine version de KNACSS.

La bonne nouvelle est que la toute nouvelle version de la grille de KNACSS a été entièrement refondue. Elle est actuellement en beta, testable ici : http://knacss.com/grillade/ et de nombreuses nouvelles fonctionnalités apparaissent, notamment celle de pouvoir définir une taille à chaque enfant... ce que devrait pouvoir t'intéresser ;)
