### ISSUE TITLE
grillade.css et knacss.css

### ISSUE THREAD

**Issue by Interned** [alsacreations/KNACSS#213]
Bonjour,

Est-il attendu de ne pas retrouver les styles CSS de grillade dans la feuille de Knacss ?

**Comment by raphaelgoetter** [comment]
Hello,

C'est prévu de l'intégrer dès la prochaine version : https://github.com/alsacreations/KNACSS/issues/207
En attendant, on le teste encore un petit peu ;)

**Comment by Interned** [comment]
Oups, désolé. Merci !

**Comment by raphaelgoetter** [comment]
Pas de souci :)
