### ISSUE TITLE
Fichier .scss dans /css

### ISSUE THREAD

**Issue by 7studio** [alsacreations/KNACSS#214]
Bonjour Raphaël,

La tache Gulp `grillade` crée actuellement un fichier `grillade.scss` dans le répertoire `/css/` lors de son exécution. 

Pour éviter ce désagrément, il suffit de supprimer `.pipe(gup.dest('./css/'))` après la concaténation :grin: Il n'y a pas besoin de déplacer/créer le fichier `.scss` pour continuer le processus de création du fichier `.css`.

**Comment by raphaelgoetter** [comment]
Hello,

Merci pour l'idée, mais finalement je trouve pratique de retrouver le fichier d'origine `.scss` : il peut être pratique pour certains.
