### ISSUE TITLE
Question sur la dernière version de knacss et compatibilité avec les vieux navigateurs

### ISSUE THREAD

**Issue by simogeo** [alsacreations/KNACSS#215]
Bonjour,
Je sais que Knacss ne s'occupe plus depuis plusieurs versions déjà de la compatibilité avec des vieux navigateurs ignorants des standards (et désuets).

Néanmoins, est-ce que la dernière version (6) est supporté par ces vieux navigateurs lorsqu'on utilise modernizr ?
Merci

**Comment by raphaelgoetter** [comment]
Bonjour,

Effectivement, KNACSS est de plus en plus basé sur des spécifications incompatibles avec les anciens navigateurs (Flexbox, `rem`, `calc()`, etc.).

Par contre, je ne suis pas sûr de comprendre ta question et le rapport avec Modernizr.

Modernizr ne fait que détecter si un navigateur supporte une feature ou non.
En clair Modernizr va t'informer que Flexbox, `rem` et `calc()` ne sont pas reconnus sur un ancien navigateur mais ça s'arrêtera là : il ne va pas rendre compatible Flexbox avec ces navigateurs par magie.

Ce sera à toi ensuite d'envisager les solutions de repli (transformer les flexbox en float par exemple).

Ai-je répondu à ta question ? Ou bien suis-je à côté de la plaque ? :)

**Comment by simogeo** [comment]
Merci pour ta réponse, 
Tu n'es pas du tout à coté de la plaque - c'est moi qui suis un peu outdated ....

Et sais-tu si la combinaison de html5shiv et css3pie (ou cssSandpaper par exemple) permet d'utiliser knacss6 sereinement y compris avec les anciens navigateurs ? 

Beau boulot en passant, knacss est une belle librairie.

**Comment by raphaelgoetter** [comment]
Ce n'est pas aussi simple que cela : 

- html5shiv ne se charge que d'assurer le support de certaines balises HTML5 (nav, header, footer, section, etc.) et n'a aucun impact sur CSS
- css3pie ne tient compte que de quelques propriétés CSS de décoration (coins arrondis, dégradés, ombrages, que des trucs purement esthétiques) : http://css3pie.com/documentation/supported-css3-features/

Or dans un outil tel que KNACSS, il y a énormément de fonctionnalités "modernes", notamment Flexbox, rem,  calc(), :nth-child(). La liste est très longue, il faudrait quasiment une solution alternative pour chacune de ces fonctionnalités.

**Comment by simogeo** [comment]
Merci pour tes précisions, c'est bien plus clair !
