### ISSUE TITLE
Souci responsive.scss

### ISSUE THREAD

**Issue by matthiasetc** [alsacreations/KNACSS#216]
Bonjour,
Est-ce normal que la partie medium screen dans le fichier responsive.scss soit
`@media (min-width: ($small + 1)) and (max-width: $large)` et pas `@media (min-width: ($small + 1)) and (max-width: $medium)` ?

Toute la partie medium est perdue actuellement

**Comment by raphaelgoetter** [comment]
Bonsoir,

Quel que soit le choix d'intervalles, il y aura un truc perturbant.

Pour l'instant, tous les intervalles sont couverts ainsi : 

- large screens  correspond à `@media (min-width: ($large + 1))`
- medium screens  correspond à `@media (min-width: ($small + 1)) and (max-width: $large)`
- small screens  correspond à `@media (min-width: ($tiny + 1)) and (max-width: $small)`
- tiny screens  correspond à `@media (max-width: $tiny)`

Avec les valeurs suivantes : 

```
$tiny: 544px !default; 
$small: 768px !default;
$medium: 1024px !default;
$large: 1200px !default;
```

Si je modifie le breakpoint "medium" comme tu le proposes : 

- il y aura un trou non couvert entre medium et large
- le breakpoint nommé "large" devra correspondre à `@media (min-width: ($medium + 1))` et sera bien moins intuitif

Je ne suis pas vraiment sûr qu'il y ait une solution. Peut-être vaut-il mieux utiliser les Mixins "Alias" dans ton cas ? https://github.com/alsacreations/KNACSS/blob/master/doc/07-responsive.md

**Comment by matthiasetc** [comment]
Je pense qu'il y a deux solutions possibles
La plus lourde : rajouter un étage 'extra-large screens' pour bien redécouper chaque étape (overkill)
La plus simple : créer un mixin custom
`@function breakpoint($bp) {
  @else if $bp == '' {
    @return '(min-width: #{$medium + 1 }) and (max-width: #{$large})';
  }
}` 

Est-ce une solution adéquate ?

**Comment by raphaelgoetter** [comment]
En toute honnêteté je ne vois pas comment utiliser ce mixin concrètement (tu constates que je suis vraiment débutant en Sass)

**Comment by mtancoigne** [comment]
Bonjour,
@matthiasetc , d'après ce que je vois, _responsive.scss prépare à ces _points de rupture_:

```txt
                                                     
      Tiny      >=[$tiny]<    Small    >=[$small]<     Medium    >=[$large]<    Large
```
La partie medium devrait fonctionner puisqu'entre le point de `small+1` et de `$large`...
je ferais un test (je débarque sur knacss, donc c'est ce post est mon premier tour d'horizon...)

**Comment by matthiasetc** [comment]
@mtancoigne 
Oui, mais y a quelque chose d'illogique, ça devrait être Medium >=[$medium]

**Comment by raphaelgoetter** [comment]
> Oui, mais y a quelque chose d'illogique, ça devrait être Medium >=[$medium]

Certes, mais comme je te l'ai dit, si on "corrige" Medium, ce sera Large qui ne sera plus logique :/

Au final, je pense que c'est toi qui as raison, je vais certainement switcher.

**Comment by matthiasetc** [comment]
Il faut voir ce qui est le plus logique
Ce qui est problématique c'est qu'un intervalle n'est pas correctement visé et que créer un nouvel intervalle extra-large-screen semble être un tantinet exagéré...
A voir, faut faire des tests, peut-être changer de fonctionnement, à méditer

**Comment by mtancoigne** [comment]
Avec ce test, on voit que la partie "Large", est remplacée par la partie médium : https://jsfiddle.net/t1kd09nf/
