### ISSUE TITLE
Push & Gouttière

### ISSUE THREAD

**Issue by Leomaradan** [alsacreations/KNACSS#217]
J'ai une grille avec gouttière (.grid-12 .has-gutter). Un de mes éléments à la classe .push

La marge du .push n'est pas appliqué

La marge affiché est celle du selecteur
`@media (min-width: 545px)
[class*=" grid"].has-gutter > *, [class^="grid"].has-gutter > * {
    margin-right: 15px;
    margin-left: 15px;
}`

Donc spécificité 0-0-2-0, la ou .push (et .pull) n'est qu'en 0-0-1-0

J'ai résolu localement le problème en augmentant artificiellement la spécificité de .push et .pull

**Comment by raphaelgoetter** [comment]
Bonsoir,

Oui je vois le problème.

Je pense effectivement qu'il est nécessaire de forcer ainsi : 
```
.push {margin-left: auto !important;}
```
