### ISSUE TITLE
.grid-item-first et *-last et leurs enfants héritent de classes non voulues

### ISSUE THREAD

**Issue by PhilippeVay** [alsacreations/KNACSS#222]
Lorsqu'ils sont un enfant de `.grid`, **`.grid-item-first`** et **`.grid-item-last`** (qui rajoutent un `order: -1` ou `+1` pour chambouler leur ordre d'affichage par rapport à celui du code HTML) matchent la règle de grillade : 
```
[class*=" grid-"],
  [class^="grid-"] {
    display: flex;
    flex-direction: row;
    flex-wrap: wrap;
    // …
}
```

Leurs enfants matchent également : 
```
  [class*=" grid-"],
  [class^="grid-"] {
    // …
    & > * {
      box-sizing: border-box;
      min-width: 0;
      min-height: 0;
    }
}
```
situées dans [_grillade.scss ligne 11](https://github.com/alsacreations/KNACSS/blob/master/sass/grids/_grillade.scss#L11-L22)

**Codepen :** http://codepen.io/PhilippeVay/pen/oYbvYL?editors=1100

**=>** ces classes ne devraient pas pouvoir être confondues par grillade avec celles créant un système de grille (`.grid` et `.grid-quelque-chose`) ou autrement dit `.grid-quelquechose` devrait être réservé aux *flex containers* créant une grille.  
Je pense que le plus simple est de les renommer (parce que rajouter des `:not([class*="grid-item-"])`, comment dire...) ? Ça ne respectera pas une notation à la SMACSS m'enfin `.one-fourth` non plus et ici c'est cette notation qui pose problème. Et la grille n'est pas un module ou composant mais un *réceptacle à modules* ^_^  
Propales : `item-grid-last`, `item-last`, `pos-grid-last`, `last-grid-item`.

**Comment by raphaelgoetter** [comment]
Ah oui, carrément. Bien vu !

**Comment by PhilippeVay** [comment]
Modification que tu as faite : 

> renommage `grid-item-*` en `item-*` pour éviter les conflits

_[Relevant commit](https://github.com/alsacreations/KNACSS/commit/4eec65bf89c73db65ce6edd3a86ba87c1a8ff5b0)_
