### ISSUE TITLE
[grillade] .grid--reverse ne fonctionne pas avec .has-gutter (ni tout seul)

### ISSUE THREAD

**Issue by PhilippeVay** [alsacreations/KNACSS#224]
Définir une gouttière avec `.has-gutter` sur une grille multi-ligne inversée `.grid-N` fonctionne bien.
Par contre sur une grille mono-ligne, cela ne fonctionne dans chacune de ces 2 éventualités : 

    <div class="grid grid--reverse has-gutter">
      (…)
    </div>
    
    <div class="grid--reverse has-gutter">
      (…)
    </div>

**[Codepen](http://codepen.io/PhilippeVay/pen/PbzPZQ?editors=1100)**

En multi-ligne, chaque flex item a une marge à gauche et une marge à droite tandis que le flex container a des marges horizontales négatives.

En mono-ligne, les flex items à partir du 2e (`> * + *`) ont une marge à gauche tandis que le flex container n'a rien de particulier.
Si, dans le 1er cas, on ajoute une classe `.grid--reverse` tout en conservant `.grid`, la marge sur les flex items à partir du second reste à gauche alors qu'il ne la faudrait qu'à droite. Ou plus simple faire comme pour les grilles multi-lignes : marge négative et répartir les gouttières à gauche et à droite.
Si, dans le 2nd cas, on ajoute le suffixe `--reverse`, on ne matche plus `.grid` et d'autres soucis apparaissent.

1er cas : je propose d'appliquer les mêmes marges que la mixin pour les grilles multi-lignes (sans appliquer les largeurs bien entendu), soit en dur : 

```
.has-gutter[class*="grid-"][class*="--reverse"] {
  margin-left: -0.5rem;
  margin-right: -0.5rem;
  & > * {
    margin-left: 0.5rem;
    margin-right: 0.5rem;
    background-color: lightgreen;
  }
}
```
2e cas : je propose d'appliquer aux flex items de `.grid--reverse` la même chose qu'à `.grid` (`display: flex` est déjà appliqué grâce au sélecteur `[class^="grid-"]` et pour les marges, voir le 1er cas)

```
.grid,
.grid--reverse {
  & > * {
    flex: 1 1 0;
    box-sizing: border-box;
    min-width: 0;
    min-height: 0;
  }
}
```

**Comment by raphaelgoetter** [comment]
Hello,

Merci pour ces tests très complets.

Pour le 2è cas, ça me semble être plutôt une bonne solution en effet.

Par contre, le cumul de la triple classe pour résoudre le 1er cas me refroidit pas mal. Je vais essayer d'y réfléchir, mais pour le moment ça me semble être bien alambiqué et complexe pour traiter un souci que je présume assez rare.

Je me dis que c'est vraiment pas évident de résoudre simplement des cas multiples :)

**Comment by PhilippeVay** [comment]
Le but n'est pas de corriger les 2 problèmes mais au moins un des 2 et le 2e cas répond plus à ce que dit la documentation de grillade : vous mettez .grid pour du monoligne et vous ajoutez --reverse pour inverser la grille. Sauf que comme ça plante actuellement dans les grandes largeurs, j'ai inventé le 1er cas où il y a encore "grid" tout court et également --reverse mais en 2 bri... euh 2 classes.
Résoudre le 2e cas seul (et compléter/éclaircir la documentation à ce sujet) suffira ;)

**Comment by raphaelgoetter** [comment]
fix 2e cas ajouté
