### ISSUE TITLE
Fichier de variables

### ISSUE THREAD

**Issue by JulesAlexiu** [alsacreations/KNACSS#225]
A la génération d'un nouveau projet, la tâche Gulp pour la compilation du fichier Sass retourne une erreur (voir la capture).
Certaines variables sont indéfinies dans le fichier _base.scss.

![bug_variables_knacss](https://cloud.githubusercontent.com/assets/13271375/20489084/a83415b2-b009-11e6-8f23-2769be8cf805.png)

**Comment by raphaelgoetter** [comment]
corrigé ? (v 6.0.4)
