### ISSUE TITLE
grillade et safari 

### ISSUE THREAD

**Issue by laBecasse** [alsacreations/KNACSS#226]
Salut tout le monde !
J'ai eu un problème avec grillade et la classe `.grid-4-small-2` avec Safari version <=8. J'ai corrigé le problème en changeant le code suivant : 
```
   [class*=" grid-"],
    [class^="grid-"] {
        display: flex;
        flex-direction: row;
        flex-wrap: wrap;

    & > * {
      box-sizing: border-box;
      min-width: 0;
      min-height: 0;
    }
}
```
par le code suivant : 
```
   [class*=" grid-"],
    [class^="grid-"] {
        display: -webkit-flex;
        -webkit-flex-direction: row;
        -webkit-flex-wrap: wrap;
        display: flex;
        flex-direction: row;
        flex-wrap: wrap;

    & > * {
      box-sizing: border-box;
      min-width: 0;
      min-height: 0;
    }
  }
```

**Comment by raphaelgoetter** [comment]
Bonjour,

Oui en effet, les fichiers `.scss` ne sont pas préfixés : https://github.com/alsacreations/KNACSS#préfixes-navigateurs

**Comment by laBecasse** [comment]
ha j'avais pas vu, merci.

**Comment by PhilippeVay** [comment]
Bonjour,

je te recommande d'ajouter à Autoprefixer le support navigateur exact que tu souhaites, cela évitera en plus que d'un coup la version N-1 d'un navigateur ne soit plus supportée par ton projet parce qu'une version N+1 est apparue… Autoprefixer utilise le standard [Browserslist](https://github.com/postcss/autoprefixer#browsers) (c'est le même auteur ^^)

Dans le [gulpfile.js](https://github.com/alsacreations/KNACSS/blob/master/gulpfile.js#L17) il y a 2 occurences (lignes 17 pour KNACSS et 32 pour grillade). Extrait de ce que j'utilise pour un client : 

    // Browserslist string of supported browsers. Given parameter for Autoprefixer
    var browsersList = ['IE >= 10', 'Edge >= 12', 'Chrome >= 42', 'Firefox >= 42', 'Firefox ESR', 'Safari >= 8', 'ios_saf >= 8', 'Android >= 4.4'];
    (…)
      .pipe(autoprefixer({browsers: browsersList}))
    (…)

Je vais proposer un PR à KNACSS et bretzel ; d'une part j'ai remarqué que sur un PR de SkullMasher, il avait une propriété préfixée en plus (IE10 je suppose) et d'autre part KNACSS annonce une compatibilité et il y a un outil qui existe pour ça, autant en profiter :) Bref c'est le genre de détail qui te fait perdre 1H mini à te demander pourquoi "ça marche pas sur telle version"

**Comment by laBecasse** [comment]
Merci @PhilippeVay, je n'ai pas tout compris. Pour ceux qui comme moi débutent avec Gulp, je conseille de suivre ce [tuto](http://www.alsacreations.com/tuto/lire/1686-introduction-a-gulp.html). 
Du coup, c'est quoi les paramètres par défaut de autoprefixer ? Quel est le support CSS par défaut ?

**Comment by PhilippeVay** [comment]
Voici les [valeurs par défaut](https://github.com/ai/browserslist#queries) (au point 4).

> If the above methods did not produce a valid result, Browserslist will use defaults: > 1%, last 2 versions, Firefox ESR.

Je ne vois plus IE dans la liste des navigateurs (mais pas non plus dans la liste "Autres") du coup je ne sais pas si IE0+11 ont disparu (par défaut) mais tant qu'ils représentent chacun plus de 1%, chacun y sera. Mmh, plus le cas d'IE10

Les parts de marché ont pour référence http://caniuse.com/usage-table

**Comment by laBecasse** [comment]
Merci pour ta réponse, je pense garder cette configuration, qui me semble raisonnable. 
En ce qui concerne IE10, il fait encore partie des 2 dernières versions d'IE, dont il doit encore être supporté, si j'ai tout bien compris.
