### ISSUE TITLE
Nécessité de redéfinir font-family pour h1 et h2 ? 

### ISSUE THREAD

**Issue by kursusHC** [alsacreations/KNACSS#227]
Bonjour et merci pour cet excellent outil qu'est KNACSS. 

Je remarque que dans la version précompilée (j'utilise la v6.0.4) la propriété `font-family` est redéfinie pour h1 et h2. Y a-t-il une utilité à ça ? 

En l'état cela empêche d'appliquer proprement sa propre police à tout le site via un simple 

    body {font-family: 'mapolice', fallback} 

car il faut overrider h1, h2, .h1-like et .h2-like. Je passe mon temps à dire à mon équipe que l'utilisation de font-family doit être expressément justifiée pour éviter ce genre de problème, mais je passe aussi mon temps à louer les bienfaits de KNACSS, donc je me retrouve bien embêté ! Merci.

**Comment by raphaelgoetter** [comment]
Mais c'est rudement pertinent, ça en effet. Je m'attelle à modifier au plus tôt. Merci :)

**Comment by PhilippeVay** [comment]
Propale : il ne serait nécessaire de déclarer une `font-family` sur ces titres et classes que si `$font-stack-headings` est différent de `$font-stack-common`

**Comment by raphaelgoetter** [comment]
@PhilippeVay ah ouais, tu veux dire avec une condition dans le fichier scss ? Pas bête.

**Comment by raphaelgoetter** [comment]
en attendant, j'ai opté pour la version simple :)

**Comment by raphaelgoetter** [comment]
Modification à venir (merci @PhilippeVay ) : 

```
h1, .#{$kna-namespace}h1-like {
  @if $font-stack-headings != $font-stack-common {
    font-family: $font-stack-headings;
  }
}

h2, .#{$kna-namespace}h2-like {
  @if $font-stack-headings != $font-stack-common {
    font-family: $font-stack-headings;
  }
}
```
