### ISSUE TITLE
word-wrap et hyphens

### ISSUE THREAD

**Issue by raphaelgoetter** [alsacreations/KNACSS#228]
Pour gérer les débordements de contenus, il est (était) recommandé d'utiliser la combinaison de deux déclarations : `word-wrap: break-word` et `hyphens: auto` (avec préfixes), la seconde étant moins bien supportée : http://caniuse.com/#search=hyphens

Mais ça c'était avant que `word-wrap: break-word` devienne systématiquement prioritaire sur `hyphens: auto` si les deux sont appliqués (quel que soit l’ordre et même avec un `!important` sur `hyphens`.

Du coup, la classe appliquée actuellement sur KNACSS est aujourd'hui complètement inutile :
https://github.com/alsacreations/KNACSS/blob/master/sass/library/_misc.scss#L26

```// hyphens on tiny screens
@media (max-width: $tiny) {
  /* you shall not pass */
  div,
  textarea,
  table,
  td,
  th,
  code,
  pre,
  samp {
    word-wrap: break-word;
    hyphens: auto;
  }
}
```

:(

La méthode qui fonctionnerait (bien plus tordue) serait :
```
div {
  word-wrap: break-word;
}
@supports (-webkit-hyphens: auto) or (-ms-hyphens: auto) or (hyphens: auto) {
  div {
    word-wrap: normal;
    -webkit-hyphens: auto;
    -ms-hyphens: auto;
    hyphens: auto;
  }
}
```

Test en ligne (CodePen) : http://codepen.io/raphaelgoetter/pen/aBLQeL?editors=1100

**Comment by nico3333fr** [comment]
Yop, tu as testé avec quels navigateurs ?

Note qu'en plus, ta solution serait au poil... sauf que je ne suis même pas sûr que Chrome n'annonce pas supporter la propriété ``` hyphens ``` sans être incapable de la gérer, vu qu'il n'embarque pas de dictionnaire de césure. 👎 

Je fais un test, et je te tiens au jus.

**Comment by nico3333fr** [comment]
Ouf, à priori, Chrome ne fait pas n'importe quoi, il ne supporte pas du tout hyphens : http://codepen.io/nico3333fr/pen/JbrzPX

**Comment by raphaelgoetter** [comment]
En fait j'avais testé sur Chrome, Safari et Firefox sur Mac et tout était OK.
Là je viens de tester sur Chrome et Firefox Windows et le code ne fonctionne pas : le mot n'est pas coupé et pourtant `@supports` est bien reconnu :(

**Comment by nico3333fr** [comment]
Salut @raphaelgoetter ,

je me suis permis de reprendre cette idée pour Röcssti du coup, je viens de committer tout ça : https://github.com/nico3333fr/ROCSSTI/issues/28 ;)

Au plaisir !

**Comment by raphaelgoetter** [comment]
\o/
