### ISSUE TITLE
Les marges ne fonctionnent pas sur mon Nokia 3210

### ISSUE THREAD

**Issue by Frasir** [alsacreations/KNACSS#229]
En WAP, le background n'est pas droit et je vois des kiwis partout. 
(Pardon Raphaël, ceci n'est qu'un test d'Issue, on découvre GitHub en formation. Bisou).

**Comment by raphaelgoetter** [comment]
Bisou à toi également !

**Comment by Frasir** [comment]
Ha, on a trouvé. Il fallait changer de téléphone. 
Merci. reBisous.
