### ISSUE TITLE
Couleur du lien au survol

### ISSUE THREAD

**Issue by jnoesser** [alsacreations/KNACSS#232]
Par défaut dans Knacss les liens changent de couleur au `:hover`, `:focus` et `:active`. 

Toutes les maquettes graphiques ne prévoient pas forcément ce type d'effet au survol, cela nous oblige donc à surcharger ce style à chaque fois. La solution serait peut-être d'appliquer une condition sur la couleur au survol (si `$link-hover-color != $link-color` ou si `$link-hover-color` n'existe pas, conserver la même couleur).

**Comment by PhilippeVay** [comment]
Excellente idée !

J'ai préparé un PR qui compile ou pas cette règle selon la valeur de `$link-hover-color` mais par contre je n'ai rien trouvé dans le cas où cette variable n'est pas définie : la compilation plante :(

Deux cas dans lesquels la règle ne fait pas partie des CSS compilées : `$link-hover-color` vaut **false** ou **`$link-color`**

**Comment by PhilippeVay** [comment]
Mis à jour avec les cas : 
* la variable n'est même pas définie (**commentée**)
* ou vaut **null**

headings : yop mais autre sujet, autre PR steup' :)
