### ISSUE TITLE
Mettre à jour la doc sur o-media

### ISSUE THREAD

**Issue by bdavidxyz** [alsacreations/KNACSS#234]
le fichier _media.scss contient le pattern classique "media css", mais il manque un exemple d'utilisation.

**Comment by bdavidxyz** [comment]
j'ai fini par trouver http://codepen.io/raphaelgoetter/pen/KMWWwj?editors=1100 peut être mettre un lien directement dans le code source ?

**Comment by raphaelgoetter** [comment]
Bien vu, je m'en occupe
