### ISSUE TITLE
un exemple de projet open-source ?

### ISSUE THREAD

**Issue by bdavidxyz** [alsacreations/KNACSS#235]
Sur la landing de KNACSS (knacss.com), il y a des exemples de très gros sites qui utilisent KNACSS, mais pas de projet moyen ou relativement conséquent qui soient open-source, ce qui constituerait un "showcase" bien sympathique.

**Comment by raphaelgoetter** [comment]
Hello.
C'est vrai.

Ceci dit, le principe est d'afficher les "plus gros" projets sur la home (si tu en connais du même acabit en open source, on est preneur).
Le reste des projets a un site dédié : http://madewith.knacss.com/

**Comment by PhilippeVay** [comment]
...où l'on trouve https://cozy.io qui est une jeune pousse mais avec un produit/projet _open source_
