### ISSUE TITLE
Quelques questions

### ISSUE THREAD

**Issue by EpocDotFr** [alsacreations/KNACSS#238]
Tout d'abord merci pour KNACSS, c'est un outil super cool. Et aussi pour son nom qui est génial 😉

J'ai utilisé Bootstrap pendant longtemps, ce n'est que récemment que j'ai décidé de tester KNACSS (après avoir passé quasi un an à me taper le CSS à la mano de mes projets...) pour [ce projet](https://github.com/EpocDotFr/server-patrol) si vous êtes curieux(se).

J'ai bien aimé KNACSS, cependant j'ai quelques questions concernant les choix de design :

  - Pourquoi ne pas avoir laissé une marge aux `<p>` ? Par défaut, tout est collé l'un sur l'autre. Valable aussi pour les `<table>`, obligé de définir soit-même les marges pour que ça soit espacé par rapport au contenu au-dessus ou en-dessous. 
  - Les tableaux ont un `table-layout` par défaut à `fixed`, pourquoi ?
  - Pourquoi les grilles monolignes ont forcément des colonnes de la même largeur ? Je crois avoir essayé de définir la largeur par exemple de la première colonne, sans succès.

Merci :)

**Comment by raphaelgoetter** [comment]
Hello @EpocDotFr et merci pour ces retours d'usager :)

> Pourquoi ne pas avoir laissé une marge aux <p> ?

Techniquement, seule la marge haute est supprimée, pas la basse, donc rien de devrait être collé.
Cette décision a été prise de très longue date pour faciliter les placements verticaux des éléments et éviter les calculs et mélanges / fusions entre les margin-bottom de l'élément précédent et le margin-top de l'élément en cours. Nous avons trouvé que cette solution était un bon compromis.

> Les tableaux ont un table-layout par défaut à fixed, pourquoi ?

Parce que c'est une bénédiction. Pour éviter que les contenus n'éclatent les cellules et pour améliorer la performance d'affichage.
cf. http://fr.slideshare.net/goetter/vive-les-tableaux-de-mise-en-page à partir de la page 62
ainsi que http://goetter.tumblr.com/post/14353041612/le-tableau-html-ce-grand-incompris

> Pourquoi les grilles monolignes ont forcément des colonnes de la même largeur ? 

Normalement tu devrais pouvoir fixer une taille sans problème. cf. http://codepen.io/raphaelgoetter/pen/EyvbqA

**Comment by EpocDotFr** [comment]
> Techniquement, seule la marge haute est supprimée, pas la basse, donc rien de devrait être collé.

D'accord, j'ai dû passer à côté d'un soucis de mon côté alors.

> Parce que c'est une bénédiction. Pour éviter que les contenus n'éclatent les cellules et pour améliorer la performance d'affichage.

D'accord, du coup quand je défini la largeur d'une colonne, cette largeur sera respectée quel que soit le contenu ?

> Normalement tu devrais pouvoir fixer une taille sans problème.

Oups, je suis passé à côté de ces classes 😀

**Comment by raphaelgoetter** [comment]
> D'accord, du coup quand je défini la largeur d'une colonne, cette largeur sera respectée quel que soit le contenu ?

Oui <3

> Oups, je suis passé à côté de ces classes

La doc : http://knacss.com/grillade/ ;)

**Comment by EpocDotFr** [comment]
>> D'accord, du coup quand je défini la largeur d'une colonne, cette largeur sera respectée quel que soit le contenu ?

> Oui <3

Cool ! Et si je veux qu'une colonne spécifique soit en mode largeur auto ?

> La doc : http://knacss.com/grillade/ ;)

_Alles gute, merci !_

**Comment by raphaelgoetter** [comment]
> Cool ! Et si je veux qu'une colonne spécifique soit en mode largeur auto ?

"normalement" il suffit de ne pas donner de largeur explicite à cette colonne/cellule et elle devrait être en largeur auto.

**Comment by EpocDotFr** [comment]
Merci :)
