### ISSUE TITLE
Flex-basis ?

### ISSUE THREAD

**Issue by aladeuil** [alsacreations/KNACSS#242]
Après lecture de grillade, je vois que flex-basis n'est pas employé et que les calc() s'effectue avec un retrait de 0.01px la plupart du temps.
Pour ma culture personnelle, quelles en sont les raisons ? En voulant tester sur un projet, je me suis rendu compte que tout ne fonctionnait pas sur Mac / Safari < 9. Il y a-t-il une relation ?

**Comment by raphaelgoetter** [comment]
Hello !

Flex-basis n'est volontairement pas employé sur KNACSS pour des raisons de compatibilités IE10 et IE11 (et parfois safari / android) actuellement.

Si tu vas sur https://github.com/philipwalton/flexbugs tu constateras qu'il y a plein de bugs en rapport avec flex-basis : 4, 7, 8 et 13 !

Bonne journée :)

**Comment by aladeuil** [comment]
Merci pour ta réponse Raphaël. Qu'en est-il du .01px sur les déclarations avec calc() ?

**Comment by raphaelgoetter** [comment]
C'est une correction d'un bug de IE : cf. https://github.com/alsacreations/KNACSS/blob/master/sass/grids/_grillade.scss#L8
