### ISSUE TITLE
Erreur de compilation Sass "Invalid US-ASCII character "\xC3" et "(Line 81 of app/sass/knacss/library/_styling.scss: Invalid US-ASCII character "\xE2")"

### ISSUE THREAD

**Issue by Taver** [alsacreations/KNACSS#244]
Je viens juste de télécharger via NPM "Knacss" et j'ai eu ce soucis lorsque j'ai commencé à compiler avec gulp-compass : 

- Invalid US-ASCII character "\xC3
- Line 81 of app/sass/knacss/library/_styling.scss: Invalid US-ASCII character "\xE2"

En cherchant rapidement sur le web, j'ajoute cette ligne avant tout contenu dans "knacss.scss"
@charset "utf-8" et la première erreur se résout entrainant la seconde.

J'ai essayé plusieurs choses (maj des gem, ajout dans le config.rb, etc) sans succès. J'ai finalement trouvé la solution en ré-enregistrant les fichiers "knacss.scss" et "library/_styling.scss" en UTF-8 with BOM. 

Je poste ici en espérant que cela aide d'autres personnes.

**Comment by raphaelgoetter** [comment]
Bonjour, je pense que l'explication vient du fait que le compilateur Sass de KNACSS (libsass) est différent de celui de Compass (ruby) : https://github.com/alsacreations/KNACSS/issues/197

Compass est encore utilisé de nos jours ?
