### ISSUE TITLE
Possible erreur dans _responsive.scss

### ISSUE THREAD

**Issue by mamashi** [alsacreations/KNACSS#245]
Bonjour,

Je viens de télécharger knacss et j'essayais d'utiliser la fonction grid-X-small-Y sans succès j'ai remarque que dans _responsive.scss il ya :

```
/* medium screens */
/* -------------- */

@media (min-width: ($small + 1)) and (max-width: $large) {

  /* layouts for medium screens */
  .#{$kna-namespace}medium-hidden {
    display: none !important;
  }
....
}
```
Le problème (arrêté moi si je me trompe) j'ai l'impression est le suivant :
@media (min-width: ($small + 1)) and (**max-width: $medium**)

**Comment by raphaelgoetter** [comment]
Hello,

Je comprends ce que tu veux dire, ça a déjà été l'objet d'une discussion (https://github.com/alsacreations/KNACSS/issues/216) et c'est un peu plus compliqué qu'on ne le croit au final :)

**Comment by PhilippeVay** [comment]
Fichu _clash_ entre la logique informatique et nous autres humain.e.s : 
 
Il y a 4 points de rupture `$tiny`, `$small`, `$medium` et `$large` ce qui crée 5 intervalles : 

1. en deçà de `$tiny`
2. entre `$tiny` et `$small`
3. entre `$small` et `$medium`
4. entre `$medium` et `$large`
5. au-delà de `$large`

Si je dis ou si on me dit "dans une petite résolution" (ou "étroit" ou "largeur avec faible nombre de pixels", etc), je comprend "en deçà d'un certain point de rupture".  
À l'inverse un truc "large", je comprend "plus large qu'un point défini comme référence".  
À l'inverse si on tente de me dire "Large c'est moins que `$large`" je vais pas comprendre. 😶   
"Petit, large" sont des manières de voir les choses vieilles comme le monde et notre langage est défini ainsi depuis quelques centaines ou milliers d'années. On définit tout par rapport à nous: un chat c'est _plus petit_ que nous la référence ; un éléphant _plus grand_.

On va donc pas amha se passer facilement de dire (et définir) "petit/étroit" comme `<` _plus petit que_ et "large" comme `>` _plus grand/large que_. Mobile first ou desktop first peu importe, il vient un moment où on passe de l'un à l'autre et _paf pastèque 🍉_. On a pas 50 termes à notre disposition non plus pour décrire ces points et intervalles, ça n'aide pas.  
Dans l'immédiat il manque un 5e terme pour décrire l'intervalle 4. entre `$medium` et `$large` ou pour peut-être décrire autre chose mais en tout cas 5 intervalles = nécessité de 5 termes.  
Ensuite je suis d'avis qu'il faut conserver "large" tel quel : `> $large`.  
Partant de là, je pense qu'il faudrait soit un nouveau terme pour `< $tiny` (et "tiny" deviendrait `> $tiny`) :

`  ???     $tiny    (Tiny)      $small     (Small)     $medium   (Medium)    $large    (Large)`

ou bien un nouveau terme pour décrire à la fois le point de rupture avant _large_ et l'intervalle en deçà de ce point de rupture.

`  (Tiny)      $tiny    (Small)    $small     (Medium)    $medium    (???)     $???    (Large)`

Dans chacun des 2 cas, on a une cohérence pour 4 des 5 cas et soit le tout premier soit le tout dernier intervalle est différent _mais au moins le point de rupture n'a pas le même nom_ (sachant que comme dit ci-dessus on ne peut pas être cohérent pour les 5 : "au-delà de 0" on s'en fiche et "en deçà de euh 4000 ou 65536px" pareil)
