### ISSUE TITLE
Idée : aligner les helper de flexbox sur ceux de Bootstrap 4

### ISSUE THREAD

**Issue by bdavidxyz** [alsacreations/KNACSS#246]
Les helpers de flexbox de bootstrap 4 sont très complets, en plus de pouvoir être utilisés avec du responsive. Je suggère d'écrire les mêmes, où à défaut d'offrir le même (très large) choix, pour ainsi permettre une très grande souplesse dans leur utilisation. Je sens que KNACSS me "force" à utiliser telle ou telle propriété de flexbox en mode "non sémantique".

**Comment by raphaelgoetter** [comment]
Bonjour @bdavidxyz et merci pour cette idée.

Ne connaissant pas (ou trop peu) les helpers de Boostrap, te serait-il possible de me citer les équivalences ou de me fournir un lien ?

Bonne journée :)

**Comment by bdavidxyz** [comment]
https://v4-alpha.getbootstrap.com/utilities/flexbox/

**Comment by PhilippeVay** [comment]
Ca commence à ressembler à de l'Atomic CSS autant de helpers 😁   
Au point que ça fait beaucoup je trouve (quoique ça va se gzipper particulièrement bien donc ce n'est pas un argument valable) mais malgré ça je trouve que j'ai assez souvent besoin de plus : flex-basis aux petits oignons en particulier. Je regarderai semaine prochaine qu'est-ce que j'utilise de Flexbox dans nos projets actuels...

**Comment by bdavidxyz** [comment]
Effectivement. On peut voir les choses de 2 façons : 
- il y en a trop
- il y en a beaucoup, mais c'est la responsabilité de chacun d'utiliser uniquement ce qui l'intéresse pour ne pas "sombrer" dans l'abus de helper.

C'est plutôt la 2ème option qui est intéressante.

**Comment by raphaelgoetter** [comment]
C'est justement un point important que celui de la concision.

KNACSS se définit lui-même comme un "anti-usine à gaz" à la Bootstrap. Du coup, c'est forcément un peu contradictoire de vouloir y ajouter 145 (oui j'ai compté) classes utilitaires juste pour Flexbox :/

Je pense qu'il va falloir trouver un compromis.

**Comment by bdavidxyz** [comment]
C'est vrai que j'ai adopté KNACSS justement parce que le ticket d'entrée était très bas, très peu de choses à retenir, la cheatsheet qui tient sur une feuille A4 c'est parfait.

Comme compromis possibles:

- faire "à la inuit" des extensions qui sont dans un autre repo
- faire des utilitaires qui "montrent la voie", et ça reste facile pour le développeur de développer ses propres helpers. Par exemple le helper .mtxl n'existe pas, mais c'est facile de le rajouter car .mtl existe et que $extra-large existe. Donc pour les flexboxes, développer une base cohérente mais réduite de helpers, avec dans les commentaires des suggestions pour étendre les helpers.

**Comment by PhilippeVay** [comment]
J'ai testé l'ajout de ces classes dans KNACSS v6 (v6.0.5 je crois).  
Il y a 3 fichiers de BS4 concernés : `_variables`, `mixins/_breakpoints` et `utilities/_flex`

- `_variables` : il faut y récupérer la liste `$grid-breakpoints`
- `mixins/_breakpoints` : sont nécessaires d'une part la `@function breakpoint-min` et d'autre part la fonction `breakpoint-infix` et la mixin `media-breakpoint-up`
- `utilities/_flex` : il faut c/c tout le fichier, c'est-à-dire la boucle `@each`

En terme de poids (en octets), j'obtiens : 

`_flex.scss` | Non-minifié | Minifié<br>gzippé
-------------|-------------|------------------
sans         | 24521       | 5016
avec         | 42103       | 6178

On ajoute donc à KNACSS minifié et gzippé seulement **1162 octets** (+23,1 %), merci la compression !

Avis : cette méthodologie donc ces classes ne correspondent pas à mes besoins pros - cette année du moins - et je ne me vois pas les utiliser. Les 2 projets principaux sont la création de 2 styleguides et donc d'une collection de composants.  
Dans un cas (énorme client), nous avons pas mal carte blanche sur la méthodologie, le markup et les CSS mais ensuite le code HTML doit être très stable tandis que les CSS peuvent évoluer plus facilement : agir sur les classes HTML est plus compliqué.  
Dans l'autre cas (site e-commerce), le styleguide est un préalable à la production de gabarits de page et la certitude que le code HTML/CSS est bien modulaire. Flexbox y est utilisé mais pas tant que ça ; faut que je regarde plus en détail à l'occasion :D

**Comment by bdavidxyz** [comment]
Est-ce que tu peux partager ton essai ? Je suis intéressé pour essayer.

**Comment by bdavidxyz** [comment]
@PhilippeVay J'ai suivi tes conseils, ça marche presque bien. Il manque dans ton tuto : copier/coller de ```/utilities/_display.scss```

Alors effectivement ça fait un nombre de helper impressionant pour une utilité discutable. Toutefois on pourrait avoir des helpers de flex non-responsive, et les aligner sur ceux de bootstrap. Cette issue amène plusieurs questions à @raphaelgoetter : 

- Pourquoi les suffixes responsifs sont-ils réservés à grillade, et pas aux helpers (margin, visibility, etc) ni à flexbox ?
- Ne pourrait-on pas aligner le vocabulaire de KNACSS sur celui de Bootstrap 4 pour une meilleure prise en main - dans la mesure du raisonnable, bien sûr.  Par exemple, "medium" chez Bootstrap c'est 768px, et large 992, alors que pour KNACSS medium c'est 991... Autre exemple, le helper pour dire "display:flex" c'est "d-flex" en Bootstrap, et chez KNACSS c'est "flex-container"


Thanks !

**Comment by raphaelgoetter** [comment]
Shippé en version 6.1.2

**Comment by PhilippeVay** [comment]
Pour m'éviter de rechercher une 2e fois les infos que je cherchais sans succès : 

(changelog [v6.1.2](https://github.com/alsacreations/KNACSS/blob/6.1.2/changelog.md))

> - alignement des helpers flexbox sur ceux de Bootstrap (`.d-flex`, `.flex-row`, `.flex-column`, `.mr-auto`)
> - alignement des breakpoints sur ceux de Bootstrap (576, 768, 992, 1200) et réorganisation des intervalles

[diff des 4 helpers Flexbox](https://github.com/alsacreations/KNACSS/commit/689c3d32f79465b6445c993552bad53c825c5ef9#diff-a733e29fb70294df9b6deaa79cb29193)
