### ISSUE TITLE
Road to KNACSS v7

### ISSUE THREAD

**Issue by raphaelgoetter** [alsacreations/KNACSS#253]
SPOILER : https://knacss.com/styleguide.html

Avis / critiques / suggestions : laissez un comm'

# idées en vrac

- encore besoin du fichier responsive.scss ?
- revoir architecture parce que ce n'est pas intuitif (_vendor, _config, objects, library, etc.)

# ce qu'on garde de KNACSS v6

- Sass, variables
- autogrid (passer de flexbox à grid layout)
- media object ?
- box-sizing
- html font-size 62.5%

# ce qu'on ajoute

- styles de base des composants (tabs, buttons, select, badge)
- JS snippets (tabs, nav) : intégration de pépin ? https://github.com/alsacreations/pepin
- des bouts de grilles en Grid Layout

# ce qu'on adapte

- grillade : a-t-on encore besoin d'un grid framework ? prévoit-on une version "alternative" pour les anciens navigateurs ?

# À piocher ailleurs
- beaucoup de bonnes idées à piocher dans https://shoelace.style/ (à part les variables CSS car manque de compatibilité IE, à prévoir dans KNACSS v8)
- https://github.com/jonathanlevaillant/atomic-builder (nommage, catégorisation, grille)
- idées aussi dans HTML5BP : https://github.com/h5bp/html5-boilerplate/blob/5.3.0/dist/css/main.css

# @TODO 

- mettre à jour Bretzel (variables, chemins, plugins obsolètes)
- mettre à jour Schnaps.it (revoir gabarits)
- couleurs accessibles
- composants accessibles (`aria-label`)
- styleguide.html dans github
- checkbox pas aussi arrondie ✓
- ajouter des variables table-footer ✓
- détailler les commentaires associés aux types de polices (headings fonts, code fonts) ✓
- renommer `flex-container flex-container-v` en `flex-container--column` ✓
- ajouter `* {min-height: 0}` en commentaire ✓
- ajouter variables de line-height (small, medium, large) ✓
- renommer fichiers de grillade en grillade-flex et grillade-grid ✓
- ajout variables font weights ✓
- ajouter variables de z-index ✓
- compatibilité navigateurs en haut ✓

**Comment by Interned** [comment]
Bonjour,

Et ce serait prévu quand ? ^^

Pour l'intégration de **Pépin**. Mais est-ce que ce projet est suffisamment avancé ?

Plus spécifique : pour le _responsive_, est-ce qu'il y aurait à prévoir quelques snippets, comme la la navigation, telle que montrée ici : http://www.goetter.fr/nav/ ? Ou est-ce prévu avec Pépin ?

**Comment by raphaelgoetter** [comment]
C'est prévu pour l'automne.

Spoiler : https://knacss.com/styleguide.html

**Comment by PhilippeVay** [comment]
Le domaine de Fox CSS est squatté depuis plus de 6 mois :( 
La dernière capture par archive.org : https://web.archive.org/web/20160709022257/http://fox-css.com:80/documents/

**Comment by gizmecano** [comment]
> - ce qu'on supprime
>    grillade (parce que plus besoin de grid framework)

En regardant la [branche `v7`](https://github.com/alsacreations/KNACSS/tree/v7/css), je vois que les fichiers `grillade.*` sont toujours présents, complétés par des fichiers `grillade-v6.*`.

De son côté, le [fichier changelog](https://github.com/alsacreations/KNACSS/blob/v7/changelog.md#changelog-v700beta-ao%C3%BBt----2017) indique : 

> - refonte complète du système de grille (dorénavant basé sur Grid Layout)

Petite question simple afin de me comprendre l'évolution en cours : l'abandon initialement envisagé est-il toujours à l'ordre du jour ou bien est-ce que `grillade` sera toujours présent sous la forme d'un système basé sur _grid layout_ dans la version 7 à venir ?

**Comment by raphaelgoetter** [comment]
Bonjour @gizmecano 

Il ne faut pas encore se fier aux informations éparpillées concernant KNACSS v7. Le projet est encore en pleine évolution et toutes les décisions et stratégies ne sont pas encore finalisées.

_À l'heure actuelle_ Grillade existe toujours dans KNACSS v7 et il est prévu la possibilité de choisir entre l'ancienne grille (flexbox) et la nouvelle grille (grid layout).

**Comment by gizmecano** [comment]
Bonjour @raphaelgoetter 

J'avais bien compris que la feuille de route n'était pas encore totalement fixée, d'où ma question pour mieux comprendre quelle était la situation _actuelle_.

Maintenant, à la lecture de cette réponse, je saisie mieux pourquoi il existe deux variantes de `grillade` dans la branche de développement.

Merci.

**Comment by nicolasca** [comment]
Hello !

voici quelques remarques/questions se basant sur la doc en cours à cette adresse https://knacss.com/styleguide.html.

- l'ajout d'un style de base pour les éléments est agréables, même s'il est sobre. Pour un starter c'est quand même cool, car on va pouvoir tout configurer avec le fichier de variables.
Est ce que pour les <table> quelque chose est prévu ?

- je trouve que le gros plus de tout ça (étant donné que je m'en tape d'IE ^^), c'est le passage à Grid pour Grillade. C'est très appréciable.
(après comme indiqué dans la page, pour des choses complexes il faudra créer les Grid nous même, mais c'est normal)

- dans l'ensemble, qu'est qui va vraiment différencier knacss v7 et https://shoelace.style/ par exemple ?

- sinon des requêtes particulières ?
Ben au final ça concerne surtout des composants. Il y a beaucoup de trucs qui servent à rien parfois, mais c'est toujours agréables d'avoir quelque chose déjà intégrer au framework avec le style (plutot que de le faire soi même ou intégrer une truc tiers)
Par exemple: une modal, popup, ou encore des alerts/notifications mais avec un bouton pour les fermer

- et enfin...la release plutôt début automne ou plutôt automne en décembre ? Smiley biggrin

**Comment by raphaelgoetter** [comment]
Merci @nicolasca pour ces retours et compliments.

> Est ce que pour les *table* quelque chose est prévu ?

Oui c'est prévu en effet.

> (étant donné que je m'en tape d'IE ^^)

Eh oui, mais un framework doit s'adapter à pas mal de monde, pas uniquement les réfractaires à IE ;)

> dans l'ensemble, qu'est qui va vraiment différencier knacss v7 et https://shoelace.style/ par exemple ?

Excellente question. Étant donné que la v7 s'est pas mal inspirée de shoelace (j'ai d'ailleurs commité quelques trucs sur le repo de ce projet), je dirais "pas grand chose", à part que KNACSS est parfaitement adapté à nos besoins à nous au sein de l'agence Alsacréations

> Par exemple: une modal, popup, ou encore des alerts/notifications mais avec un bouton pour les fermer

C'est le point où je demeure mitigé. Il est toujours compliqué de savoir où s'arrêter dans les styles par défaut et dans la lourdeur de l'outil.

Je préfère de loin conserver un outil le plus léger possible, au détriment du style de tous ces composants dont on ne se sert presque jamais. Sinon, autant utiliser Bootstrap.

**Comment by gizmecano** [comment]
> Je préfère de loin conserver un outil le plus léger possible (...)

Personnellement tout à fait d'accord sur ce point.
Par ailleurs, rien n'empêche de créer et proposer des modules _externes_ basés sur KNACSS... 😉

**Comment by nicolasca** [comment]
Je comprends le point de vue.
Surtout quand on regarde la liste des components parfois, on se dit que 75% on utilisera pas.

C'est juste concernant ce type: tooltip/popup/modal/alert, cette catégorie là, je la trouve utile en général. Et au final ça va ajouter quoi, 4-5 kb à la lib (j'en sais rien) ?
Avec l'amélioration des connexions, des systèmes de cache (pas partout, mais globalement), je me dis que c'est un bon compromis. 
Après bon, ce sont des préférences ^^
(et oui après je pourrais créer mes modules, mais c'est pour ça aussi que je veux utiliser un framework, pour éviter cela au maximum :) )

Oh la réponse de d'Alsacien..de Normands pour https://shoelace.style/  ^^
J'imagine aussi que d'avoir un outil à soi, dont on maitrise 100%, et dont on choisit l'évolution, ça doit être important pour vous.

Et pour la date de release du coup, c'est difficile à se prononcer j'imagine ?

**Comment by gizmecano** [comment]
> (...) après je pourrais créer mes modules, mais c'est pour ça aussi que je veux utiliser un framework (...)

Juste sur ce point, je pense avoir été mal compris : je parlais bien de créer et de _proposer_ des modules de ce type.

J'avais plutôt en tête l'idée d'un framework de base aussi léger que possible, mais avec la possibilité d'y ajouter des sortes d'extensions (éventuellement validées par le gestionnaire du projet, par exemple) qui ne seraient pas des modules _personnels stricto sensu_ (i.e. spécifiquement adaptés à des projets personnels particuliers), mais pourraient venir compléter le framework (sans pour autant faire partie de la base même du projet KNACSS)...

(J'espère avoir été un peu plus explicite) 🤔

**Comment by raphaelgoetter** [comment]
C'est une super idée de laisser la place à des modules externes proposés par des contributeurs en effet.
Mais on risque d'être pointilleux (= synonyme de "chiants") sur le respect des standards, de l'accessibilité, de la sémantique, etc.

**Comment by nicolasca** [comment]
PI j'ai fait rapidement un test avec la master (sur un projet qui utilisait la v6).
J'ai vu un petit soucis de conflit avec fontawesome sur les arrows 
(de mémoire.. un soucis avec le :after pour le selector [class="*arrow]. Un truc comme ça, je ne me souviens plus exactement).
Du coup j'ai enlevé l'import de arrow dans le sass.

**Comment by raphaelgoetter** [comment]
@nicolasca Ah oui bien vu.

J'hésite encore entre : 
1- modifier le nom de la classe
2- supprimer les flèches de KNACSS
3- laisser comme ça en ajoutant un warning

Sachant que si quelqu'un utilise fontawesome, il ne va pas avoir besoin des flèches de KNACSS, elles deviennent inutiles de facto. Changer le nom de classe n'apportera rien.

Les supprimer me semble un peu radical, puisqu'elles peuvent servir à ceux qui n'utilisent pas de font-icones.

Bref, je crois que je vais pencher vers le warning.

**Comment by gizmecano** [comment]
> C'est une super idée de laisser la place à des modules externes proposés par des contributeurs en effet.
> Mais on risque d'être pointilleux (...) sur le respect des standards, de l'accessibilité, de la sémantique, etc.

Je ne vois pas en quoi c'est un _risque_ 😉 

En fait, une plateforme comme GitHub me paraît même plutôt bien adaptée, puisque la _communauté_ des utilisateurs pourrait commenter, modifier et améliorer le code de ces _modules_, et ce jusqu'à ce qu'il vous semblent suffisamment correspondre à vos critères de qualité...

Il y a même des mécanismes natifs de [revues de code](https://github.com/blog/2291-introducing-review-requests) qui me semble pouvoir parfaitement aider à mettre en place ce genre de processus.
