### ISSUE TITLE
Interrogation sur la mise en forme de l'élément `<address>`

### ISSUE THREAD

**Issue by gizmecano** [alsacreations/KNACSS#255]
Je m'interroge sur la [mise en forme](https://github.com/alsacreations/KNACSS/blob/master/css/knacss-unminified.css#L657) actuelle de l'élément `<address>`.

Quelqu'un pourrait-il expliciter les raisons ayant motivées le choix de `font-style: italic;` dans ce cas précis ? Merci.

**Comment by raphaelgoetter** [comment]
Sauf erreur de ma part, c'est pour uniformiser l'affichage de cet élément (qui me semble être (presque) partout en italique), mais qui n'est pas pris en compte dans le "reset" de NormalizeCSS.

**Comment by gizmecano** [comment]
Bizarre: j'ai justement (presque) l'impression inverse, n'ayant pas souvenir d'avoir trouvé une mise en forme en italique jusque-là (exemple dans [Bootstrap](https://getbootstrap.com/docs/3.3/css/#type-addresses)).

Surtout, je ne vois pas vraiment ce qui justifierait une telle mise en forme. Par exemple, si l'on suit la page [Wikipedia française](https://fr.wikipedia.org/wiki/Adresse_postale) sur le sujet, l'italique serait même déconseillé (il s'agit certes de la mise en forme pour le courrier, mais après tout, n'utilise-t-on pas l'italique dans les citations pour se caler sur les normes de l'imprimerie?).

Bref, je m'interroge... 🤔

**Comment by tetue** [comment]
Je me suis posé la question dernièrement… L'italique est le style par défaut recommandé par le W3C (avec `display: block;` que je ne comprends pas davantage). Comme il sert à marquer le moyen de contacter l'auteur du document HTML, typiquement dans `<footer>`, un style part défaut en normal inline serait plus pertinent. J'ai donc fait le choix d'[annuler l'italique dans Tiny Typo](https://github.com/tetue/tinytypo/commit/9c0c5ddaa6a1d60405d76265bcd8ecaafd7cf47a) et je laisse le choix de block ou inline, plus impactant, à l'appréciation de chaque codeur.

**Comment by gizmecano** [comment]
> (...) L'italique est le style par défaut recommandé par le W3C (...)

Ah, et bien voilà une référence précise qui me manquait. Merci beaucoup. Je vois d'ailleurs que cet italique est aussi présent dans la [version 5.2](https://www.w3.org/TR/html52/rendering.html#non-replaced-elements-flow-content)... 👍 

> (...) il sert, non pas à baliser les adresses postales, mais à marquer le moyen de contacter l'auteur du document HTML (...)

Certes, mais on remarque tout de même (à tout le moins dans la plupart des exemples que j'ai pu observer) que ce genre de _coordonnées_ s'avèrent souvent être les mêmes... 😉

**Comment by tetue** [comment]
La [spec HTML 5.2](https://www.w3.org/TR/html52/grouping-content.html#the-address-element) donne plus de diversité d'exemples (et, oh tiens, ne met plus en garde sur l'usage abusif sur les adresses postales !) : « The address element represents contact information for a person, people or organization. It should include physical and/or digital location/contact information and a means of identifying a person(s) or organization the information pertains to. »

**Comment by gizmecano** [comment]
> (...) La spec HTML 5.2 (...) ne met plus en garde sur l'usage abusif sur les adresses postales (...)

Effectivement... Et l'exemple 7 (avec l'utilisation de RDFa) semble bien montrer qu'on peut l'utiliser dans ce cas aussi.

Mais pour revenir au sujet initial, à partir de ces références précises, je pense que je vais chercher si des raisons ayant motivées le choix de `font-style: italic;` peuvent éventuellement s'y trouver.
