### ISSUE TITLE
[v7] Remplacer les margin-top par des margin-bottom ?

### ISSUE THREAD

**Issue by raphaelgoetter** [alsacreations/KNACSS#256]
D'après [Bootstrap v4](http://v4-alpha.getbootstrap.com/content/reboot/#approach) : 

> Avoid margin-top. Vertical margins can collapse, yielding unexpected results. More importantly though, a single direction of margin is a simpler mental model.

Jusqu'à présent, KNACSS était fondé sur une philosophie similaire (une seule direction de margin), mais par contre tout est calculé à partir de `margin-top` : 

```
/* font-sizing for content */
p,
.#{$kna-namespace}p-like,
ul,
ol,
dl,
blockquote,
pre,
td,
th,
label,
textarea,
caption,
details,
figure {
  margin-top: 0.75em;
  margin-bottom: 0;
  line-height: $line-height;
}
```

Source : https://github.com/alsacreations/KNACSS/blob/master/sass/library/_base.scss#L70

Ce serait le bon moment de se poser la question d'un switch et de passer tous les `margin-top` vers des `margin-bottom`, ça éviterait notamment de devoir écrire un peu plus loin que tous les `:first-child` doivent avoir un `margin-top: 0;` non ?

**Comment by SkullMasher** [comment]
Passer sur margin-bottom ne me dérange pas. Je n'avais pas eu de difficulté à gérer le rythme vertical sur mon site en v6.

J'ai relu [l'article de Harry](https://csswizardry.com/2012/06/single-direction-margin-declarations/) à ce sujet. Je partage au cas ou.
