### ISSUE TITLE
[v7] Remplacer normalize.css par reboot.css ?

### ISSUE THREAD

**Issue by raphaelgoetter** [alsacreations/KNACSS#257]
Bootstrap propose dorénavant son fichier de "reset" : reboot.css

Après l'avoir parcouru et lu quelques articles élogieux à son égard (dont https://scotch.io/tutorials/a-look-at-bootstrap-4s-new-reset-rebootcss ), je remarque que reboot.css va souvent dans le sens de KNACSS, plus souvent que normalize à mon goût.

Bref, je me demande si ce ne serait pas une bonne idée de remplacer normalize.css par reboot.css

- scss : https://github.com/twbs/bootstrap/blob/v4-dev/scss/_reboot.scss
- css : https://github.com/twbs/bootstrap/blob/v4-dev/dist/css/bootstrap-reboot.css

BONUS TRACK : utiliser les variables de reboot.scss ? https://github.com/twbs/bootstrap/blob/v4-dev/scss/_reboot.scss

**Comment by SkullMasher** [comment]
Je préfère garder la taille des titres dans l'ordre comme Normalize. Qu'en pensez vous ?

Super le système de variables de gestion de margin-bottom.

"Bonus track": [Codepen comparateur Meyer VS Normalize VS Reboot](https://codepen.io/ncerminara/embed/RLMwmy?height=500&slug-hash=RLMwmy&default-tabs=html,result&host=https://codepen.io&embed-version=2)

**Comment by raphaelgoetter** [comment]
Hello,

Je viens de voir le comparateur (beau boulot !). Il semble que les bizarreries des titres soient dues au user agent stylesheet qui modifie la taille des `<h1>` dès lors qu'ils sont descendants de `<section>`... mais sans toucher aux autres niveaux de titres.

Quoi qu'il en soit, reboot ne serait pas appliqué tel quel sans repasser sur certains détails (comme c'était le cas avec normalize)
