### ISSUE TITLE
Problème avec Dreamweaver 2017.0.1

### ISSUE THREAD

**Issue by PlasticLove13** [alsacreations/KNACSS#258]
Bonjour,  
En utilisant Knacss SASS avec DW, j'ai l'erreur suivante :

`Error: Invalid US-ASCII character "\xE2"
  on line 85 of /Users/passager/SITES/• Nouveau SITE KNACSS/css/library/_styling.scss
  from line 41 of /Users/passager/SITES/• Nouveau SITE KNACSS/css/style.scss`

Lignes : 
83: q,
84: .#{$kna-namespace}q {
85:   quotes: "“\00a0" "\00a0”";

Quelqu'un a une idée ?… 
—poke @raphaelgoetter 

D'avance, merci. Bisous.

**Comment by raphaelgoetter** [comment]
Hello,

d'après mes rapides recherches, ce serait a priori un problème avec Python (je suppute que le compilateur Sass de DW est en python) : https://stackoverflow.com/questions/21639275/python-syntaxerror-non-ascii-character-xe2-in-file

**Comment by PlasticLove13** [comment]
Arf -.-" 
Merci @raphaelgoetter
