### ISSUE TITLE
Grillade : défilement horizontal indésirable

### ISSUE THREAD

**Issue by ymdk01** [alsacreations/KNACSS#259]
Bonjour,

Lorsque j'utilise une grille de largeurs égales (grid-2 par exemple) avec une gouttière (has-gutter-xl), un défilement horizontal apparaît (Firefox et Chrome, pas testé d'autres navigateurs).

Il suffit de se rendre sur le site même de KNACSS pour s'en rendre compte :

https://knacss.com/grillade/

Modifiez la largeur du navigateur et vous verrez apparaître le défilement horizontal.

Sinon, voyez ici : 

https://codepen.io/anon/pen/GOBpZM

D'où cela provient-il ?

**Comment by PhilippeVay** [comment]
Bonjour,

Avec une gouttière de 4rem entre 2 colonnes, il y a également une demie-gouttière de part et d'autre de la grille (2rem à gauche, 2rem à droite) et c'est ce qui crée ce défilement horizontal.

En ajoutant 2rem de padding horizontal sur le parent (`body` ou un `.wrapper` à créer), on visualise ces demies-gouttières et supprime le défilement, par exemple https://codepen.io/PhilippeVay/pen/WXgxEy

```
body {
  margin: 0 2rem;
  background-color: beige;
}
.has-gutter-xl > * {
  margin-bottom: 1rem;
  background-color: tomato;
}
```
