### ISSUE TITLE
https://knacss.com/KNACSS-cheatsheet.pdf not found

### ISSUE THREAD

**Issue by 6clicks** [alsacreations/KNACSS#260]
je sais pas si c'est bien ici que je doit remonté l'info mais sure le site l'url pour le  pdf mène un une page 404 

Sachez qu'un Pense-bête en PDF est disponible pour vous souvenir des classes utiles de KNACSS.

**Comment by raphaelgoetter** [comment]
Hello, 

Merci pour l'info. J'ai placé ce lien sur plusieurs pages, pourrais-tu me dire à partir de laquelle il y a une 404 ?

Par exemple, ici le lien fonctionne : 
- https://knacss.com/
- https://github.com/alsacreations/KNACSS
- https://www.alsacreations.com/actu/lire/1755-KNACSS-v7-est-sorti.html

**Comment by 6clicks** [comment]
C'est dans la doc.  
https://knacss.com/styleguide.html
en dessous du cadre bleu dans installation.

**Comment by rair** [comment]
En fait l'url directe vers le pdf donne aussi 404 pour moi

**Comment by raphaelgoetter** [comment]
@6clicks OK bien vu, corrigé

@rair : Oui mais l'erreur provient de quelle page source ?

**Comment by rair** [comment]
aucune ... j'avais juste l'url en mémoire du navigateur. Mais maintenant la feuille a un nom incluant la version.

**Comment by raphaelgoetter** [comment]
@rair Oui, j'ai préféré ajouter le numéro de version.

L'avantage est que les versions 6 (et 3) sont toujours récupérables.
