### ISSUE TITLE
grillade : pour .grid-N, commentaire et code ne sont pas d'accords

### ISSUE THREAD

**Issue by PhilippeVay** [alsacreations/KNACSS#262]
Dans [grillade-grid.scss](https://github.com/alsacreations/KNACSS/blob/2490a5dfe58b7b94f2e6cd38f08f0d4208109106/sass/_library/grillade-grid.scss#L38-L43), il y une incohérence entre ce qu'annonce le commentaire et ce que fait la boucle : de 1 à 12 ou de 2 à 12 ?

On retrouve bien `.grid-1` dans la CSS générée.

```scss
// grid constructor (.grid-2 to .grid-12)
@for $i from 1 through 12 {
```

Dans grillade v6, il n'y a pas de `.grid-1` et la boucle commence bien à 2.

Ici je suppose que la boucle devrait également commencer à 2 ? Même s'il n'y a plus de `.grid`, ce n'est pas du tout équivalent à `.grid-1` (mono-ligne forcé vs mono-colonne) donc je ne trouve pas d'utilité à `.grid-1`. `.grid-1-small-4` serait bizarre... Un `.grid-v` où tu peux modifier l'ordre des items via `.item-(first|last)`, ajouter `--reverse` et jouer avec `grid-auto-columns` ? Mouais...

**Comment by raphaelgoetter** [comment]
Je passe à 2, tu as raison.

> Même s'il n'y a plus de .grid

En fait, ... https://github.com/alsacreations/KNACSS/blob/master/sass/components/_autogrid.scss#L8
