### ISSUE TITLE
Grillade : variables $small et $large définies (`!default`) mais pas utilisées

### ISSUE THREAD

**Issue by PhilippeVay** [alsacreations/KNACSS#263]
On avait parlé IRL de feu le test sur l'existence des variables de type `$bp`, que tu as supprimé dans le commit [Grillade variables little rework](https://github.com/alsacreations/KNACSS/commit/7c4ef6ebb475add872b235afce1951a2fe9e0a9d) mais j'ai remarqué un nouveau truc.

_Contexte_ pour les autres : grillade-grid.scss attribue une valeur par défaut aux variables $tiny, $small, $medium et $large **SI** elles n'ont pas déjà été définies au préalable (grâce à `!default`).  
Dans le cas habituel, elles sont définies par KNACSS dans `_variables.scss` _mais_ grillade est indépendant de KNACSS et le cas peut donc arriver où `_variables.scss` n'aura pas déjà été importé.

Code : 

```scss
// use these variables only for a standalone Grillade
// in KNACSS, you shall modify variables file instead
$tiny: 480px !default;
$small: 576px !default;
$medium: 768px !default;
$large: 992px !default;
```

Les 2 variables `$small` et `$large` ne sont pas utilisées mais sont tout de même définies.

- $tiny est utilisé pour 
  1. "activer" grillade au-delà de $tiny
  2. et `-small-N`
- $small n''est pas utilisé
- $medium est la borne supérieure de `-small-N`
- $large n''est pas utilisé

Je propose de supprimer les 2 lignes et peut-être de préciser que ces variables existent dans `_variables.scss` mais ne sont pas utilisées dans grillade.  
`// $small and $large (defined in _variables.scss if you're importing this file) aren't used in grillade. Only $tiny and $medium are.`

EDIT : ça simplifie de possibles tests : 

- si $tiny n'est pas défini, lui attribuer une valeur par défaut
- si $medium n'est pas défini, lui attribuer une valeur par défaut
- est-ce que les 2 ont la même unité ?
- dans ce cas, est-ce que `$tiny < $medium` ? (sinon tant pis, continuer la compilation)

**Comment by raphaelgoetter** [comment]
OK je supprime les 2 lignes, en attendant un test plus complet
