### ISSUE TITLE
Attribut spécifique à KNACSS ?

### ISSUE THREAD

**Issue by raphaelgoetter** [alsacreations/KNACSS#265]
Je viens de constater que la nouvelle version de BluePrint [utilise des attributs HTML dédiés (`.bp=""`)](https://blueprintcss.io/docs/grid).

Après mon étonnement (surtout parce que ce n'est pas valide HTML), je me suis rappelé que d'autres font pareil : Angular et son `ng-`, ou VueJS et son `v-`.

Finalement, je me dis que ce n'est pas si bête : 
- ça permet d'avoir un namespace simple (ex. `knacss-grid="3"` ou `knacss="grid-3"`)
- ça permet d'avoir un système complètement dédié aux grilles par exemple, sans empiéter sur les classes

Des avis quelqu'un ? :)

**Comment by PhilippeVay** [comment]
D'un strict point de vue **accessibilité**, le RGAA ne l'interdit pas : [Code valide](http://references.modernisation.gouv.fr/rgaa/glossaire.html#code-valide)

> Sauf indication contraire, les attributs non répertoriés par les spécifications sont non applicables.

D'un point de vue personnel / **projets d'inté HTML/CSS** : 

* les classes (me) conviennent avec la complexité actuelle de grillade (et avec Grid Layout la complexité / les possibilités ne va/vont plus augmenter je suppose)
* KNACSS n'a pas vocation à être utilisé avec d'autres frameworks et en particulier grillade qui peut être très facilement commenté et remplacé par un autre système de grille ou par Grid Layout. On se dirige vers 0 système de grilles plutôt que 2 donc bon...
* dans les projets clients type O***a, le layout de la page repose sur des éléments avec des classes `.zone-N` et chaque élément ancêtre des composants pour faciliter l'intégration dynamique par le.la client.e : pas de conflit en vue. Dans un composant (nav et footer par exemple), pas plus de problème en vue.
