### ISSUE TITLE
Styles composants - optionnel

### ISSUE THREAD

**Issue by roadto2002** [alsacreations/KNACSS#266]
Bonjour,

Les styles par défaut sont plutôt embêtant surtout quand on utilise une charte graphique différente. On est obliger de surcharger ses derniers et jouer avec le poids des sélecteurs.

Est-il possible d'avoir la possibilité d'embarquer ou pas les styles composants (button ...) ? Avoir une version Knacss configurable comme il y a pu avoir par le passé ?

**Comment by raphaelgoetter** [comment]
Bonjour,

Oui c'est tout à fait possible. Tu peux choisir de ne pas importer les fichiers de composants, au cas par cas : https://github.com/alsacreations/KNACSS/blob/master/sass/knacss.scss

**Comment by roadto2002** [comment]
Merci pour le retour
