### ISSUE TITLE
[Doc] .grid ne fait plus partie de grillade

### ISSUE THREAD

**Issue by PhilippeVay** [alsacreations/KNACSS#267]
La documentation a une section intitulée grillade mais qui concerne aussi `.(auto)grid`.

Dans la documentation de KNACSS :
* le titre de section est [Grillade](https://knacss.com/styleguide.html#grids)
* après une présentation de grillade et un comparatif v6/v7 : "Voici quelques exemples de grilles réalisées avec KNACSS v7…"
* la 1ère partie est `.autogrid` / `.grid`
* puis `.grid-6` et autres classes définies par grillade

Certes la phrase d'introduction décrit bien toutes les parties comme faisant partie de KNACSS mais le titre de la section est grillade.

Pistes :

* il vaudrait mieux que ce titre de section soit "Grille(s)" ou bien
* expliciter le fait qu'.(auto)grid fait partie de KNACSS mais pas de grillade ou bien 
* faire d'autogrid une section à part ?

**Comment by raphaelgoetter** [comment]
ou bien intégrer autogrid dans Grillade ?

**Comment by PhilippeVay** [comment]
Si ça a du sens pour toi, oui.  
Bonus : `$gutter` ne serait définie qu'une fois.

Mais je verrais quand même bien 2 parties pour la doc : .(auto)grid et grillade v6/v7. Ou bien déplacer l'intro après .autogrid ? Le comparatif voire  l'intro ne concernent pas tant que ça .autogrid...

**Comment by raphaelgoetter** [comment]
> Si ça a du sens pour toi, oui.

C'est ce qui me paraît le plus intuitif.

**Comment by raphaelgoetter** [comment]
ah, résolu au fait
