### ISSUE TITLE
Des tests pour KNACSS (enfin déjà grillade)

### ISSUE THREAD

**Issue by PhilippeVay** [alsacreations/KNACSS#268]
J'ai commencé à créer des _test cases_ pour grillade (à terme pour KNACSS) dans ma branche [philippevay/test-grillade](https://github.com/PhilippeVay/KNACSS/tree/test-grillade/test) avec Pug/Jade.

Le but est de détecter à terme ce qui casse dans une future version (avant release), quand j'aurai implémenté des tests de régression visuelle

Pour cela, je vais utiliser [BackstopJS](https://github.com/PhilippeVay/KNACSS/tree/test-grillade/test) qui utilise Chrome Headless (il peut aussi utiliser Gecko/Firefox mais la compatibilité _cross-browsers_ n'est pas tellement le but de ces tests-ci, en tout cas c'est de faible priorité ici).  
Pour terminer les tests de grillade, il manque les tests de `small-N` (ex : tester que `.grid-4-small-2` a bien  4 colonnes sur desktop et 2 sur "tablette". Tester qu'avec `.grid-4` il y a tout le temps 4 colonnes est prêt mais pas `small-`)  
Ensuite il y aura les tests de KNACSS en commençant par une bonne grosse page avec tous les éléments HTML. Cela permettra de tester facilement les CSS stylant les éléments. Le coeur de KNACSS ne se prête peut-être pas à des tests _visuels_ ; il faudra peut-être une autre approche mais à voir dans quelques temps 😃

**Comment by PhilippeVay** [comment]
J'ai pas le droit d'ajouter des labels et assignee ? Relouuu. @raphaelgoetter Si tu peux me l'assigner et ajouter "test" et ptet "TODO", merci 😃

**Comment by raphaelgoetter** [comment]
GG wellplayed thumbsup!

**Comment by PhilippeVay** [comment]
La partie backstopJS est commitée (*) mais un total de 3000 et quelques screenshots (579 tests x 6 résolutions) c'est du gros nimp' 
Et 3 x 2 Chrome en parallèle ne passent pas sur mon portable qui n'a que© 4 Go de RAM ! L'un après l'autre, ça passerait mais bon je vais pas garder 3000 screenshots...
Je revois ça et on peut en discuter 😄

**Comment by raphaelgoetter** [comment]
Je up parce que je ne sais pas où ça en est.

La nouveauté est que je prévois une version majeure v8 à la fin juillet.

**Comment by PhilippeVay** [comment]
Je clos, j'ai d'autres priorités.  
Si ça doit bouger, je réouvrirai
