### ISSUE TITLE
La classe .tag en doublon avec la classe de wordpress

### ISSUE THREAD

**Issue by htlcode** [alsacreations/KNACSS#270]
Il faudrait renommer la classe .tag car elle est utilisée dans wordpress

**Comment by PhilippeVay** [comment]
Le plus immédiat est de commenter l'import de `components/tags` dans `knacss.scss`.

@raphaelgoetter Avais-tu parlé de pouvoir désactiver tout style d'un élément via une variable ? C'était il y a quelques temps…  
Pistes : il serait possible de conditionner ces styles (tout style) à une variable de config genre `$knacss-layout: true;`  
Ou uniquement pour éviter les conflits avec un CMS (SPIP et son `.fr`, WordPress et ses tags).

**Comment by raphaelgoetter** [comment]
> Avais-tu parlé de pouvoir désactiver tout style d'un élément via une variable ?
Ce serait une piste en effet. Mais dans tous les cas, cela nécessite de tripoter la version Sass, du coup c'est tout aussi simple de commenter les partials non souhaités, non ?

**Comment by PhilippeVay** [comment]
Je pensais aux propriétés "cosmétiques" qui déclarent des couleurs et effets par opposition à des propriétés comme display voire padding mais je me rends compte que :  
> conditionner ces styles (tout style) à une variable de config genre $knacss-layout: true;

ne résoud pas le problème : il y aura quand même conflit avec un CMS.  
Reste : 
> pour éviter les conflits avec un CMS (SPIP et son .fr, WordPress et ses tags)

la possibilité d'une variable type `$cms-wordpress: true;` qui désactiverait `.tag` ou .fr pour SPIP

**Comment by raphaelgoetter** [comment]
J'affecte à la prochaine version (v8) de KNACSS
