### ISSUE TITLE
Grillade-flex, npm et IE

### ISSUE THREAD

**Issue by classikd** [alsacreations/KNACSS#271]
Bonjour,

J'utilise le framework que j'ai téléchargé depuis npm, tout fonctionne super bien, mais il y a quelque chose qui me dérange un peu. Le fait que le choix du type de grille se fasse depuis le fichier node_modules/.../knacss.scss. Si je choisis grillade-flex pour mes grilles et que je décide plus tard (ou quelqu'un d'autre) de réinstaller les dépendances de mon projet, la grille qui sera chargée ne sera plus grillade-flex mais grillade-grid, ce qui est embêtant puisque je tiens au support jusqu'à IE10. Y'a-t-il moyen de contourner ce léger problème ? 

Merci

**Comment by raphaelgoetter** [comment]
Hello,

À l'agence, nous fonctionnons de la même manière que toi.

Je te conseille comme nous d'externaliser le fichier knacss.scss (de même que les fichiers de variables) plutôt que de les laisser dans node-modules.

Tu peux t'inspirer de notre environnement (nommé Bretzel) : https://github.com/alsacreations/bretzel/tree/master/src/assets/css

**Comment by classikd** [comment]
Merci c'est parfait ! Comme j'utilise Webpack je n'ai pas pensé à jeter un coup d'oeil à Bretzel, j'aurais dû.

**Comment by raphaelgoetter** [comment]
Cool :)
