### ISSUE TITLE
-webkit-appearance/ -moz-appearance: none manquants dans forms.scss

### ISSUE THREAD

**Issue by omdevin** [alsacreations/KNACSS#275]
Bonjour,

Dans le module forms.scss, il me semble qu'il manque les entrées suivantes :

```
-webkit-appearance: none;
-moz-appearance: none;
```

Le select, dans mon cas et sous Safari, n'était pas stylé. Cela concerne la section :

```
[type="color"],
[type="date"],
[type="datetime-local"],
[type="email"],
[type="month"],
[type="number"],
[type="password"],
[type="search"],
[type="submit"],
[type="tel"],
[type="text"],
[type="time"],
[type="url"],
[type="week"],
select,
textarea {
```

J'ai regardé sur le site KNACSS v7 documentation et les propriétés sont bien présentes.

**Comment by raphaelgoetter** [comment]
Hello,

En effet, aucune propriété des fichiers `.scss` de KNACSS n'est préfixée. C'est renseigné dans la doc ici : https://knacss.com/styleguide.html#install 

Si tu n'utilises pas d'outil tel qu'Autoprefixer, alors il faudra ajouter les préfixes à la main ou te contenter des versions compilées `.css`

**Comment by omdevin** [comment]
Bonjour Raphael,

Merci, je ferai plus attention à la documentation la prochaine fois.
