### ISSUE TITLE
Placeholder

### ISSUE THREAD

**Issue by raphaelgoetter** [alsacreations/KNACSS#276]
> Depuis Firefox 51, cette fonctionnalité est implémentée via le pseudo-élément standard ::placeholder.

https://developer.mozilla.org/fr/docs/Web/CSS/::-moz-placeholder

**Comment by PhilippeVay** [comment]
`:-moz-placeholder` actuellement en place dans KNACSS ne fonctionne déjà plus avec Fx 56 et c'est OK avec `::placeholder` 👍 

Pour rappel l'ancienne version de Fx ESR était 45.x (avant l'actuelle 52.x)

**Comment by PhilippeVay** [comment]
@raphaelgoetter Il se passe des choses bizarres au passage d'Autoprefixer dans cette version 7.0.4.

Avant – [_forms.scss](https://github.com/alsacreations/KNACSS/blob/9584249ca484cc8576a0bb94abef63b1ccde68c9/sass/components/_forms.scss) : 
```
::-webkit-input-placeholder {
  color: #777;
}

input:-moz-placeholder,
textarea:-moz-placeholder {
  color: #777;
}

input::placeholder,
textarea::placeholder {
  color: #777;
}
```

Après – [knacss-unminified.css](https://github.com/alsacreations/KNACSS/blob/9584249ca484cc8576a0bb94abef63b1ccde68c9/css/knacss-unminified.css) : 
```
::-webkit-input-placeholder {
  color: #777;
}

input::-webkit-input-placeholder,
textarea::-webkit-input-placeholder {
  color: #777;
}

input:-ms-input-placeholder,
textarea:-ms-input-placeholder {
  color: #777;
}

input::-ms-input-placeholder,
textarea::-ms-input-placeholder {
  color: #777;
}

input::placeholder,
textarea::placeholder {
  color: #777;
}
```

Il y a le problème des webkit d'une part et… un petit tour sur Caniuse pour mieux comprendre ce que fait Autoprefixer 😛 

> Partial support refers to using alternate names:
>::-webkit-input-placeholder for Chrome/Safari/Opera (Chrome issue #623345)
>:-ms-input-placeholder for IE.
>::-ms-input-placeholder for Edge (also supports webkit prefix)

`-moz-` est supprimé puisqu'on ne demande pas le support de Fx 50 (j'aurai à l'ajouter dans un futur projet), dont acte.
