### ISSUE TITLE
Optimiser les SVG dans le _partial checkbox/radio

### ISSUE THREAD

**Issue by PhilippeVay** [alsacreations/KNACSS#277]
Les 2 images de coche pour .checkbox:checked et .radio:checked sont des SVG.

Le 1er est en base64 ce qui ne facilite pas une modification comme la couleur de fill. En le décodant, je me suis rendu compte qu'il y avait un commentaire XML, bref c'est optimisable : 

```
<?xml version="1.0" encoding="utf-8"?>
<!-- Generator: Adobe Illustrator 17.1.0, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 viewBox="0 0 8 8" enable-background="new 0 0 8 8" xml:space="preserve">
<path fill="#FFFFFF" d="M6.4,1L5.7,1.7L2.9,4.5L2.1,3.7L1.4,3L0,4.4l0.7,0.7l1.5,1.5l0.7,0.7l0.7-0.7l3.5-3.5l0.7-0.7L6.4,1L6.4,1z"
	/>
</svg>
```

Le disque radio est _URL-encoded_, AMHA ce serait plus simple que les 2 le soient.
Et s'il y a moyen d'utiliser des variables Sass pour les couleurs en plein milieu de la chaîne de texte, ça faciliterait grandement une rapide modif !

**Comment by raphaelgoetter** [comment]
Je pose ça là en attendant : 
https://codepen.io/raphaelgoetter/pen/LmoqYW?editors=1100
