### ISSUE TITLE
Grille

### ISSUE THREAD

**Issue by gregoirepuget** [alsacreations/KNACSS#278]
Hello,

Y a t'il moyen d'avoir des comportements différents en médium et en large ?

Par exemple : col-4-medium-6 et col-4-large-8 ?

Merci

**Comment by PhilippeVay** [comment]
Il est possible de copier-coller la [boucle qui s'occupe de small](https://github.com/alsacreations/KNACSS/blob/master/sass/_library/grillade-grid.scss#L78-L93) en changeant les points de rupture et le mot-clé small. Attention au nommage puisque dans KNACSS 7 l'intervalle "small" en ce qui concerne la grille signifie entre les points de rupture $tiny et < $medium. À conserver ou à modifier, c'est selon (sujet plus compliqué qu'il n'y parait ^^).

Si `-intervalle-` n'est actif qu'entre 2 points de rupture (MQ avec un min et un max), cette boucle peut être copiée-collée avant ou après la boucle pour small mais s'il y a 2 boucles avec juste un minimum (mobile first) ou juste un maximum, l'ordre va être important pour que l'une ait une chance d'écraser l'autre :)
