### ISSUE TITLE
_reboot.css provoque un DEPRECATION WARNING avec libsass

### ISSUE THREAD

**Issue by PhilippeVay** [alsacreations/KNACSS#282]
(libsass qui est utilisé par gulp-sass)

```
$ gulp css:main
[14:33:51] Using gulpfile C:\(snip)\bretzel\alsacreations\gulpfile.js
[14:33:51] Starting 'css:main'...
DEPRECATION WARNING on line 33, column 8 of C:/(snip)/bretzel/alsacreations/src/assets/css/knacss.scss:
Including .css files with @import is non-standard behaviour which will be removed in future versions of LibSass.
Use a custom importer to maintain this behaviour. Check your implementations documentation on how to create a custom importer.

[14:33:54] Finished 'css:main' after 2.26 s
```

edit: ➡️ [Issue dans node-sass](https://github.com/sass/node-sass/issues/2362)

En attendant la prochaine version de libsass qui elle proposera un _custom importer_ (si j'ai bien compris), je n'ai pas trouvé de moyen simple d'importer une CSS (`postcss-import` et `postcss-nested-import` ne travaillent pas avec un source Scss et pas réussi à faire fonctionner [node-sass-css-importer](https://www.npmjs.com/package/node-sass-css-importer) depuis gulp-sass).  
Utiliser un minifieur pour sa fonctionnalité "inliner des ressources" mais sans compression, minification ou restructuration serait une solution valable, s'il est possible de désactiver tout le reste…

La solution la plus simple et de loin serait de renommer `_reboot.css` en ➡️ `_reboot.scss`. Sur ce projet tu le gères à la main donc aucune tâche à mettre à jour ni rien. OK pour toi @raphaelgoetter ?

**Comment by raphaelgoetter** [comment]
OK pour moi :)

**Comment by PhilippeVay** [comment]
Plus de warning, le PR résoud bien cette Issue
