### ISSUE TITLE
Gestion des z-index sur KNACSS ?

### ISSUE THREAD

**Issue by raphaelgoetter** [alsacreations/KNACSS#284]
Pour l'instant, les niveaux de z-index de KNACSS sont gérés par ces variables : 
```
$zindex-navigation   : 1000 !default;
$zindex-dropdown     : 2000 !default;
$zindex-popover      : 3000 !default;
$zindex-tooltip      : 4000 !default;
$zindex-modal        : 5000 !default;
$zindex-notification : 6000 !default;
$zindex-debug        : 7000 !default;
```

(Source : https://github.com/alsacreations/KNACSS/blob/master/sass/_config/_variables.scss#L103 )

Il se trouve que @PhilippeVay propose une autre méthode inspirée de la source suivante : https://medium.com/openmindonline/how-i-organize-css-in-large-projects-using-ufocss-part-1-9d04417f39f3

J'ai moi-même repris l'idée en automatisant la génération des classes à l'aide d'un `each` et voilà ce que cela donnerait :

```
$layers: navigation, tooltip, modal, notifications, debug;

@each $elem in $layers {
  [class*="#{$elem}-"] {
    z-index: index($layers, $elem);
  }
}
```

Qui serait compilé ainsi :

```
[class*=navigation-] {
  z-index: 1;
}

[class*=tooltip-] {
  z-index: 2;
}

[class*=modal-] {
  z-index: 3;
}

[class*=notifications-] {
  z-index: 4;
}

[class*=debug-] {
  z-index: 5;
}
```

J'aimerais savoir si quelqu'un a une contre-indication à procéder ainsi, ou s'il n'y a que des avantages à cette méthode.

Et sinon, plus généralement, comment vous gérez les z-index chez vous ?

Merci de vos éventuels retour sur cette question :)

**Comment by DaPo** [comment]
1000 par 1000, c'est beaucoup.

Unitairement comme tu le proposes, c'est trop peu.

Pour une raison X ou Y, si j'ai besoin de mettre un élément entre `modal-*` et `notifications-*` ou autre, ça me paraît un peu casse-gueule d'y mettre un `z-index` à 3, selon la position de l'élément et tout, bon, bof c'est très contraignant à mon sens.

Alors que si tu joues avec des dizaines, qu'on est à respectivement à 30 et 40, je mets mon élément à 35 et hop, pas de souci.

C'est comme ça que je fonctionne.

**Comment by raphaelgoetter** [comment]
> Pour une raison X ou Y, si j'ai besoin de mettre un élément entre modal-* et notifications-* ou autre, ça me paraît un peu casse-gueule

Justement, dans ce cas là il suffirait d'ajouter un élément dans ta liste initiale `$layers` et c'est réglé, non ?

Ceci dit, c'est *aussi* jouable de passer de 10 en 10.

**Comment by DaPo** [comment]
Aaaaah, ouais, bon, si on devait acter, mettons que j'télécharge le CSS de ton framework et que j'ai pas de préprocesseurs, avoir les z-index de 10 en 10 c'est une sécurité appréciable.

**Comment by PhilippeVay** [comment]
J'ai pas été "inspiré" : j'ai vu la liste dans l'article et HAN§ super idée AMHA.

Perso je suis partisan de gérer d'une part les z-index globaux (de composants) uniquement via cette liste et d'autre part localement (dans un composant) de pouvoir coller des z-index à la main.  
Localement seraient autorisées les valeurs -1, 0, …, 3 grand max.  
La cohabitation entre composants se ferait avec des valeurs commençant à 1000 (arbitrairement) et de 1 en 1 : ne surtout pas laisser un intervalle afin que personne ne puisse aller coller une valeur numérique qui deviendra fausse le jour où la liste est étendue,réduite ou autre modif… C'est cette fonction qui s'occuperait de générer les z-index et leur valeur est arbitraire (n'a pas besoin d'être connue à l'avance).

Mais je n'avais pas pensé à l'utilisation de KNACSS tel quel (version CSS), cas qui ne me concerne pas voire ne m'intéresse pas. Ça me va de modifier le pas (10 ⇒ 1) dans un fichier de variables et en plus de ça d'ajouter à terme un linter qui interdit les valeurs numériques trop élevées de z-index (dans le source Scss).

Générer autant de classes qu'il y a d'items dans la liste Sass (à l'avance, que le composant soit là ou pas) ou les générer à la demande via une fonction Sass : je préférerais la dernière solution (pas de classe inutile) mais la 1ère me conviendra presque autant ; c'est du détail dont gzip ne fera qu'une bouchée 😄

**Comment by tzi** [comment]
Sur mon dernier projet, on est parti sur quelque chose comme ça:

```scss
// We keep 1 to 9 to handle local conflict
$z-index-content: 10;
$z-index-content-over: 11;

// For layout, example: fixed header, menu
$z-index-layout: 20;
$z-index-layout-over: 21;

// For content overlay
$z-index-tooltip: 30;
$z-index-modal: 100;
$z-index-modal-over: 101;
$z-index-splash: 200;
```

Je n'aime pas trop avoir les propriétés de `z-index` loin des propriétés de `position`. Je ne suis pas fan non-plus de la "magie" qui ajoute automatiquement un z-index en fonction du nom de la classe.
Vu que je fais beaucoup de BEM, ça rend difficile l'ajout d'un `z-index` sur un élément ?
Donc je suis plus pour les variables Scss :smile_cat:

**Comment by ffoodd** [comment]
ÀMHA ces solutions de « listes » de valeurs sont trop facilement parasitées par des changements de contexte d’empilement : une position, une opacité ou une transformation qui interrompt la pile, et tout est déréglé…

Je partirai plutôt sur des classes « atomiques » (version @thierryk) comme `.z-i(1)`, `.z-i(2)` et ainsi de suite. On peut ainsi gérer les éléments au cas par cas indépendamment de leur fonction (navigation, modale, etc.) mais en fonction de la pile dans laquelle ils se trouvent.

Et conjointement, une classe pour créer une nouvelle pile :
```css
.stacss {
  position: relative;
  z-index: 1;
}
```
Ainsi, on peut : 
* créer des piles à volonté,
* les empiler les unes par rapport aux autres à l’aide de nos classes atomiques ;
* et empiler les différents éléments à l’intérieur de la même façon.

Je n’ai jamais utilisé ça, mais en lisant la discussion le besoin de gérer les contextes et pas seulement les index m’a paru être un point important. C’est d’ailleurs plus ou moins ce que propose @tzi, puisque des « sas » de valeurs intermédiaires sont préservés entre chaque groupe de variable…

Réflexion en cours !

**Comment by tzi** [comment]
Bonne remarque @ffoodd !
Je ne l'ai pas précisé, mais il y a interdiction d'utiliser ces variables en dehors du contexte d'empilement de la fenêtre :dancer: 
Si on doit gérer l'ordre dans un autre contexte d'empilement, on crée des variables locales si besoin.
