### ISSUE TITLE
Grille possible sur mobile ?

### ISSUE THREAD

**Issue by amkpgame** [alsacreations/KNACSS#285]
Bonjour,

Merci pour votre framework css efficace, rapide et facile à prendre en main.

La seule chose qui me chagrine dans un premier temps et le fait de ne pas avoir la possibilité de grille sur l'affichage mobile.

Il est parfois utile voir indispensable, même dans un projet simple, d'avoir à disposition une grille pour les petits écrans.

Par exemple, j'ai un site de jeux qui apparaissent en liste avec icone et titre, et je voudrais pouvoir en afficher 2 par lignes sur la version mobile, si j'ai bien compris (sauf erreur de ma part) Grillade ne le propose pas. Est ce prévu dans le futur ?

**Comment by raphaelgoetter** [comment]
Bonjour @amkpgame ,

Effectivement, ce n'est pas prévu pour l'instant (principalement parce que le nombre de combinaisons "options / breakpoints / gouttières" à gérer était historiquement très complexe à gérer via flexbox).

Depuis Grid Layout, les choses sont bien plus simples et c'est un enrichissement qui devient envisageable à présent (= peut-être pour la prochaine version majeure de KNACSS).

Ceci dit, je reste persuadé que pour des besoins "simples" tels que deux colonnes, l'usage d'un système de grille me paraît exagéré. Pourquoi ne pas se contenter de placer tes éléments en Flexbox ou en Grid Layout "à la main" ?

**Comment by amkpgame** [comment]
Merci pour votre réponse @raphaelgoetter

En effet, je vais donc le faire "à la main". Je privilégie toujours l'utilisation (comme tout le monde j'imagine) des fonctionnalités du framework que j'intègre, mais je devrais pouvoir faire une entorse pour mes 2 colonnes^^

**Comment by PhilippeVay** [comment]
Bonjour,

la grille s'active à partir de 480px et cette valeur est une variable `$tiny` qu'il est possible de modifier dans `_variables.scss` (la passer à 0 ou 320px) ou d'écraser dans `_library/grillade-grid.scss` (dans ce dernier cas en enlevant le `!default`) si l'on ne veut modifier _que_ grillade sans toucher à d'autres utilisations de `$tiny`.  
Mais il faut ensuite recompiler KNACSS…
