### ISSUE TITLE
[Grillade Flex] -  Flag !default sur la variable grid-gutters

### ISSUE THREAD

**Issue by arlg** [alsacreations/KNACSS#286]
Actuellement il n'est pas possible de définir une autre valeur pour la variable $grid-gutters ailleurs que dans le fichier grillade-flex.scss. (par exemple dans le _variables.scss)
Cette variable est automatiquement écrasée par celle présente dans le fichier car elle ne contient pas le flag !default.

Fix : Il faudrait ajouter le flag !default à la ligne 19.

```
// gutter values for grid layouts. Unit can be: %, px, em, rem
$grid-gutters: ( '': 1rem, '-l': 2rem, '-xl': 4rem ) !default;
```

**Comment by raphaelgoetter** [comment]
Hello,

Effectivement, c'est un sujet qui a été résolu dans la version Grid Layout (en partant du principe que les grilles flexbox étaient vouées à disparaître).

Il serait possible d'ajouter le même système que dans le fichier grillade-grid.scss 

```
// gutters
    @if variable_exists(grid-gutters) {
      $gutter: $grid-gutters !global;
    }
    @else {
      $gutter: ( '': 1rem, '-l': 2rem, '-xl': 4rem ) !global;
    }
```

**Comment by arlg** [comment]
Merci pour ta réponse et ta solution, c'est vrai que les grilles flexbox sont censées disparaître dans les mois à venir (je dois supporter IE11) . 

J'essaierai avec les grilles et la nouvelle version d'Autoprefixer (cf l'article tout frais sur Alsacréations ;) )
