### ISSUE TITLE
Textareas: white-space: nowrap et Firefox

### ISSUE THREAD

**Issue by mtancoigne** [alsacreations/KNACSS#288]
Les [textareas sont stylées avec](https://github.com/alsacreations/KNACSS/blob/ae3addebdb74c2f2e7d27a394f19609f98c90093/sass/components/_forms.scss#L43) `white-space: nowrap`, ce qui résulte dans Firefox (à priori depuis la [v36](https://bugzilla.mozilla.org/show_bug.cgi?id=1137650)) à un comportement où l'on ne peut pas faire de retours à la ligne, ni de multiples espaces...

A priori, dans Chrome tout va "bien", mais je n'ai pas pu tester moi même

D'après, le [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/white-space):
>`nowrap`
    Collapses white space as for normal, but suppresses line breaks (text wrapping) within the source.

Donc le comportement de Firefox ne semble pas trop décalé par rapport à la définition, mais ce serait bien de ne pas avoir ce comportement par défaut pour une textarea :)

J'ai fait [un codepen](https://codepen.io/anon/pen/pOqOKP) pour pouvoir tester facilement.

**Comment by raphaelgoetter** [comment]
Hello,

Remarque tout à fait pertinente. Je regarde ça immédiatement, merci !

**Comment by mtancoigne** [comment]
Il semblerait que le correctif 245992c ne corrige pas le souci les textareas restent en `white-space: normal`, ce qui équivaut en gros à nowrap, mais avec du wrapping (pas de support des multiples espaces)

(re-d'après le [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/white-space#Values))
> `normal`
Sequences of white space are collapsed. Newline characters in the source are handled the same as other white space. Lines are broken as necessary to fill line boxes.

[W3Schools](https://www.w3schools.com/cssref/pr_text_white-space.asp) rajoute que c'est la valeur par défaut; je pense que pour les inputs, pas les textareas. 

Une valeur intéressante pourrait être `pre-wrap`: retours à la ligne des lignes trop longues, mais conservation des espaces.

**Comment by raphaelgoetter** [comment]
bonne idée :)

**Comment by mtancoigne** [comment]
D'accord, je m'en occupe si tu le souhaites.

**Comment by raphaelgoetter** [comment]
Bah c'est déjà fait :)
