### ISSUE TITLE
variables des composants... dans les composants ?

### ISSUE THREAD

**Issue by raphaelgoetter** [alsacreations/KNACSS#290]
Pour l'instant, les variables spécifiques aux composants (ex. burger button) sont placées dans le fichier unique de variables.

Ne serait-il pas plus logique de les placer dans le même fichier SCSS que le composant lui-même ?

Ainsi, le fichier de variables ne contiendrait que les variables globales.

**Comment by mtancoigne** [comment]
D'un autre côté, ça demanderait de les chercher pour les connaitre (à moins qu'elles soient documentées, comme dans la [doc de Bulma](https://bulma.io/documentation/elements/box/) qui est top pour ça)

**Comment by raphaelgoetter** [comment]
> comme dans la [doc de Bulma](https://bulma.io/documentation/elements/box/) qui est top pour ça)

Ooh, c'est vrai que c'est beau ça !

**Comment by raphaelgoetter** [comment]
C'est très sympa de ta part et je suis bien évidemment preneur.
J'attends quelques potentiels retours quand même avant de lancer la machine.

**Comment by SkullMasher** [comment]
Hello, cela me semble logique également.

**Comment by mtancoigne** [comment]
Je viens de regarder un peu la doc de bulma, il semblerait qu'il n'y ait qu'une personne [qui s'en occupe](https://github.com/jgthms/bulma/blame/master/docs/documentation/elements/icon.html#L118). Avec le peu de recherche, j'en arrive à cette conclusion : soit il maintient la doc et écris le HTML, soit il le génère, et est chargé de le faire... 

J'espère que c'est la deuxième solution, dans tous les cas je vais chercher du côté des parseurs SCSS. A-t-on une stack technique pré-requise, ou si je trouve un truc en brainfuck c'est ok ?

**Comment by mtancoigne** [comment]
J'ai testé "kss-node", "sassdoc" et "sassdocjs" sans arriver à quoi que ce soit de concluant. On dirait qu'il y a toujours un truc qui coince :/

**Comment by mtancoigne** [comment]
Alors alors ? On fait quoi ?? :D

**Comment by raphaelgoetter** [comment]
Bah, je ne veux pas être pessimiste, mais s'il y a toujours un truc qui coince je ne pense pas que l'on puisse avancer pour le moment :/

**Comment by yannux** [comment]
Salut à tous, chez Bulma.io c'est un script qui permet de générer un fichier JSON par composant avec les variables : https://bulma.io/2018/06/20/automatic-variables-documentation/ 

En regardant le dépôt Git il semble que tout soit se passe ici  : https://github.com/jgthms/bulma/tree/master/docs/scripts 

Le script utils.js https://github.com/jgthms/bulma/blob/master/docs/scripts/plugins/utils.js qui permet de parser tous les fichiers sass

**Comment by raphaelgoetter** [comment]
J'affecte à la prochaine version (v8) de KNACSS
