### ISSUE TITLE
[website] [ux] le certificat SSL n'est plus valable pour knacss.com

### ISSUE THREAD

**Issue by AntoineVe** [alsacreations/KNACSS#295]
Avant de tomber dans la redirection vers "www.knacss.com", si on tape "knacss.com" on tombe sur une erreur du certificat SSL expiré. 

Sinon bravo et merci pour cet outil css !

**Comment by Gaspacchio** [comment]
Je viens de tester sur Firefox, Edge et Chrome et pas d'erreur. Le certificat doit à nouveau être valide !

**Comment by Gaspacchio** [comment]
Je propose de fermer le bug, car résolu.
