### ISSUE TITLE
Compilation

### ISSUE THREAD

**Issue by kougelhopf** [alsacreations/KNACSS#296]
Bonjour,
tout d'abord merci pour ce super outil qu'est Knacss!
Par contre depuis la version 7.0.1 je n'arrive plus à compiler mes css...  (avec  Node.js v11.3.0 ni d'ailleurs avec la v10.14.1)

J'ai essayé de compiler avec Gulp 3.9.1 (après des `warn deprecated`  de `gulp-util,` `graceful `et `minimatch` à l'installation de Gulp) lorsque je lance mon `gulp css` j'ai systématiquement :
` events.js:167
throw er; // Unhandled 'error' event
      `^`
TypeError: css.walk is not a function
    at css (D:\knacss\node_modules\knacss\node_modules\postcss-discard-comments\dist\index.js:44:13)
    at initializePlugin (D:\knacss\node_modules\knacss\node_modules\cssnano\dist\index.js:35:51)`

Y aurait-il une solution ? peut-être que je passe à côté de quelque chose,  je suis pas très familier avec Node.js et Gulp...  
J'ai également essayé avec Gulp 4.0.1 mais j'ai alors une `AssertionError [ERR_ASSERTION]: Task function must be specified`...
Je précise que tous mes essais sont faits à partir d'un knacss tout neuf, juste dézippé.

**Comment by mtancoigne** [comment]
Bonjour,

Ça passait quand même avec le même setup Gulp (même versions de dépendences) mais une Knacss plus ancienne ?

**Comment by kougelhopf** [comment]
Après quelques test :
- Knacss 7.0.5 et Gulp 3.9.1 > _Fonctionne_ 
(avec Gulp 4.0.0  `[ERR_ASSERTION]: Task function must be specified` mais si j'ai bien compris c'est une histoire d'écriture des task qui est différente depuis la v4)
- Knacss 7.0.7 et Gulp 3.9.1 > _Fonctionne également_

**Comment by kougelhopf** [comment]
Si utile, le rapport complet de l'erreur sous Knacss 7.0.1
```
[10:30:55] Using gulpfile D:\KNACSS-master\gulpfile.js
[10:30:55] Starting 'css'...
[10:30:56] gulp-postcss: knacss.css
autoprefixer: D:\KNACSS-master\sass\knacss.css:1630:5: grid-auto-flow: dense is not supported by IE
autoprefixer: D:\KNACSS-master\sass\knacss.css:1634:5: grid-gap only works if grid-template(-areas) is being used
autoprefixer: D:\KNACSS-master\sass\knacss.css:1638:5: grid-gap only works if grid-template(-areas) is being used
autoprefixer: D:\KNACSS-master\sass\knacss.css:1642:5: grid-gap only works if grid-template(-areas) is being used
autoprefixer: D:\KNACSS-master\sass\knacss.css:1650:5: grid-auto-flow works only if grid-template-rows and grid-template-columns are present in the same rule
autoprefixer: D:\KNACSS-master\sass\knacss.css:1651:5: grid-auto-columns is not supported by IE

events.js:167
      throw er; // Unhandled 'error' event
      ^
TypeError: css.walk is not a function
    at css (D:\KNACSS-master\node_modules\postcss-discard-comments\dist\index.js:44:13)
    at initializePlugin (D:\KNACSS-master\node_modules\cssnano\dist\index.js:35:51)
Emitted 'error' event at:
    at errorOrDestroy (internal/streams/destroy.js:98:12)
    at Transform.onerror (_stream_readable.js:694:7)
    at Transform.emit (events.js:182:13)
    at errorOrDestroy (internal/streams/destroy.js:98:12)
    at onwriteError (_stream_writable.js:436:5)
    at onwrite (_stream_writable.js:461:5)
    at Transform.afterTransform (_stream_transform.js:94:3)
    at Immediate.<anonymous> (D:\KNACSS-master\node_modules\gulp-postcss\index.js:93:9)
    at processImmediate (timers.js:632:19)
```

**Comment by mtancoigne** [comment]
Je ne connais pas Gulp et sa configuration, mais là, on voit un changement de version majeure (3 à 4), donc à mon sens il faudrait regarder du côté de la configuration de Gulp pour la v4?.

@raphaelgoetter, une idée, un avis ?

**Comment by raphaelgoetter** [comment]
Hello,

Je vais faire quelques tests dès que possible.
En attendant, ma version de Gulp est 3.9.1. et aux dernières nouvelles tout compilait bien.

**Comment by PhilippeVay** [comment]
Bonjour,

Gulp v4 est une version majeure qui demande des modifications (de mémoire, plus de gulp-utils, il faut remplacer 1 par 1 chaque "util" et on en utilise 3. La doc est super bien faite mais c'était pas la peine il y a 6 mois de se précipiter - sur Bretzel - à faire changer tout le monde de version donc j'avais laissé en suspens pour me consacrer à d'autres modifs…).  
Le genre de problème, en particulier avec "fs.events" je l'ai eu plein de fois, plutôt avec des changements de version de node ou en voulant reprendre de "vieux" projets mais je pourrais pas/plus dire qu'est-ce qui a résolu le souci à chaque fois :/ Plein de bidouilles et une fatigue quand ça revient…

J'ai pu compiler KNACSS 7.0.1 et 7.1.0 sur Win 10 Pro x64 avec :

```
$ node -v && npm -v
v10.3.0
6.4.1
```

**Comment by raphaelgoetter** [comment]
Avec la même config que @PhilippeVay *mais sur un Mac*, la compilation plante chez moi.

Première piste : en commentant CSSnano (le minifieur) dans le gulpfile ça fonctionne.

**Comment by raphaelgoetter** [comment]
OK, il y avait bien un problème avec CSSnano qui était mal configuré si on tentait une compilation avec  `gulp css` ...
*Mais* en fait on n'est pas censé compiler avec gulp css mais plutôt avec `gulp cssDev` ou `gulp cssProd`.

J'ai fait un patch 7.1.1 qui assigne la tâche `gulp` (default) aux bonnes tâches à présent. Chez moi ça fonctionne avec les instructions suivante : 

- `gulp` (dev + prod + grillade flex + grillade grid)
- `gulp cssDev` (--> KNACSS unminified)
- `gulp cssProd` (--> KNACSS minified)
