### ISSUE TITLE
knacss 7.1.0 / grillade & problème de mise en page IE 11-12

### ISSUE THREAD

**Issue by simogeo** [alsacreations/KNACSS#297]
Bonjour,
Je viens de faire une mise à jour de knacss 6.x vers 7.1.0 ... et tout va bien sauf pour IE. 

J'ai bien lu le chapitre consacré à Grillade : https://www.knacss.com/doc.html#grids
Je pensais pouvoir faire une sorte de test conditionnel pour savoir quel système de grille renvoyer mais visiblement ça ne fonctionne pas. Il y a t'il un truc simple ? 

Je suis surpris de ne pas trouver de thread similaire sur le sujet. 
Merci pour le retour.

simo

**Comment by raphaelgoetter** [comment]
Bonjour Simo,

Peux-tu me confirmer que ton bug d'affichage est provoqué par l'usage d'une grille ? ( car je ne suis pas sûr que l'emploi d'une grille soit justifié dans ce genre d'affichage)

> Je pensais pouvoir faire une sorte de test conditionnel pour savoir quel système de grille renvoyer mais visiblement ça ne fonctionne pas.

Quel genre de test ? Les commentaires conditionnels ne fonctionnent plus depuis IE10 par exemple.

> Il y a t'il un truc simple ?

Le plus simple, et le plus radical, est de se contenter de la version grille en Flexbox, qui devrait marcher partout, même sur le version 7 de KNACSS

J'attends de tes retours pour affiner.

**Comment by simogeo** [comment]
> Peux-tu me confirmer que ton bug d'affichage est provoqué par l'usage d'une grille ? ( car je ne suis pas sûr que l'emploi d'une grille soit justifié dans ce genre d'affichage)

Oui, c'est bien pas l'usage d'un grille. En fait, autogrid n'est pas interprété par la version fex apparemment

> Quel genre de test ? Les commentaires conditionnels ne fonctionnent plus depuis IE10 par exemple.

en effet, enfin, je le fais côté serveur en testant le navigateur.
Du coup, je charge la version complète de knacss et si browser == IE 10 || IE 11 j'appelle aussi grillade-flex ....

Ca fonctionne à peu près, si ce n'est cette limite sur autogrid ... que j'ai remplacé par la classe `grid` pour avoir un résultat convenable.

pas moyen d'avoir un fallback directement dans knacss pour assurer la compatibilité ?
AVec ce genre de hack ? 

https://philipnewcomer.net/2014/04/target-internet-explorer-10-11-css/

Merci pour ton retour

**Comment by raphaelgoetter** [comment]
>  j'appelle aussi grillade-flex 

Je pense que c'est un gros souci: Si tu charges grillade-grid *et aussi* grillade-flex, il y aura sans aucun doute des conflits car il n'est pas prévu que les deux cohabitent.

Si ton test fonctionne, il faut vraiment qu'il ne charge que l'une des deux versions.

> pas moyen d'avoir un fallback directement dans knacss pour assurer la compatibilité ?
> AVec ce genre de hack ?

Ce serait possible en effet, mais... ne le prends pas mal... ce serait une énorme concession en terme de lourdeur de code (des media queries partout et inutiles pour 98-99% des visiteurs).

Je préfère conseiller de se limiter à la version Flexbox si la compatibilité IE est encore un point crucial.

**Comment by simogeo** [comment]
oui, oui, je comprends bien que tu ne souhaites pas gérer cela ;-) et ce serait dégrader la qualité et la maintenabilité de knacss.

Malheureusement, j'ai des clients qui souhaitent cette compatibilité avec IE .... dois-je nécessairemment compiler moi-même ou je puis-je directemenent remplacer le code CSS  ? J'ai essayé mais ce n'était pas très concluant ...

A minima, il serait intéressant de fournir une version compilée -css minifié - utilisant flexbox, genre un fichier `knacss.alt.css` basé sur flexbox, non ?

Merci pour tes retours précieux.

**Comment by raphaelgoetter** [comment]
IE11 commence à être vraiment problématique, et clairement pas adapté à Grid Layout, même avec des outils comme Autoprefixer.

**Si** tes contraintes sont : 
- uniquement d'utiliser Autogrid, alors il est possible de remplacer cette partie à la main (mais c'est fastidieux je te l'accorde)
- d'employer toute la grille (Grillade) de KNACSS, et que tu peux compiler toi-même, il suffit de n'intégrer que la version du fichier .scss Flexbox
- d'employer toute la grille (Grillade) de KNACSS, et que tu ne souhaites pas compiler toi-même, c'est effectivement plus compliqué. Je me note en tâche de prévoir encore une nouvelle version spéciale pour ce genre de cas, mais j'ai bien peur que cela ne soit pas dans mes priorité (comme tu l'as bien compris je crois ;) )

**Comment by simogeo** [comment]
Oui, IE a, durant son existance, toujours été problématique en fait ... ;-)

Je souhaterai employer toute la grille, a minima avoir une version compatible IE.
Je vais voir si je peux compiler. Je ne suis pas très familier de sass / gulp mais je suis tombé sur [ce tuto](https://www.alsacreations.com/tuto/lire/1686-introduction-a-gulp.html) !

Merci,

**Comment by simogeo** [comment]
Salut @raphaelgoetter, est-ce que ça veut dire que tu renonces à proposer une version compilée pour IE 10 ou c'est dans les tuyaux ? (Je dois reconnaitre que je n'ai pas pris le temps d'essayer de mon côté )

**Comment by raphaelgoetter** [comment]
Faire une version dédiée à IE10 est malheureusement une tâche qui me prendrait bien trop de temps, seul, pour une population qui avoisine aujourd'hui 0.13% en France et 0.07% dans le monde.

Je te propose donc, à défaut de meilleure solution, d'envisager l'option déjà évoquée : "d'employer toute la grille (Grillade) de KNACSS, et que tu peux compiler toi-même, il suffit de n'intégrer que la version du fichier .scss Flexbox"
