### ISSUE TITLE
Radio bug sur Safari

### ISSUE THREAD

**Issue by florianbouvot** [alsacreations/KNACSS#298]
Bonjour,

En consultant la documentation du projet j'ai remarqué que les radio ne fonctionnaient pas sur Safari : la puce ne s'affiche pas au clic.

Testé sur MacOS 10.14.2:
- Safari 12.0.2 : bug
- Chrome et Firefox 👍

Si vous avez besoin d'autres infos...

Merci,
Florian.

**Comment by raphaelgoetter** [comment]
Hello,

En effet, je confirme qu'il y a un souci d'affichage sur Safari.
Je l'ai isolé ici : https://codepen.io/raphaelgoetter/pen/LmoqYW

Je vais voir ça en détail mais pour le moment je n'ai aucune piste (stackoverflow n'est pas mon ami, semble-t-il) :/

**Comment by Coralielm** [comment]
Reçu par mail (via Sébastien) :"Un clic sur un bouton radio prend bien en compte la valeur cochée, mais en revanche le bouton radio ne s'affiche pas comme étant coché à l'écran. Si le formulaire contenant ce bouton radio est validé, lorsque la page est rechargée, le bouton radio apparaît en revanche bien coché.

[...]

Le navigateur utilisé est Safari 12.0.3 sur Mac [...]."

**Comment by raphaelgoetter** [comment]
Selon toute évidence c'est un bug du navigateur, mais je ne trouve aucune ressource à ce sujet.

**Comment by jeanbaptistevilain** [comment]
Hello,

A toutes fins utiles, j'ai constaté que le bug Safari provenait spécifiquement de l'attribut background-image qui n'était pas pris en compte correctement par le navigateur dans ce cas précis de changement d'état.
Cela semble lié à l'URL encodée en base64, car si on la remplace par une URL d'image "classique" le bouton radio s'affiche comme souhaité. A court terme, ça fait un contournement relativement simple à mettre en place. 

Merci pour tout le boulot sur KNACSS !

**Comment by raphaelgoetter** [comment]
Ah c'est bon à savoir, merci pour cette piste très intéressante !

**Comment by raphaelgoetter** [comment]
J'affecte à la prochaine version (v8) de KNACSS

**Comment by raphaelgoetter** [comment]
Bonne nouvelle, le bug semble résolu sur Safari 13 \o/
