### ISSUE TITLE
Webpack erreur de compliation

### ISSUE THREAD

**Issue by darkiron** [alsacreations/KNACSS#299]
Bonjour un petit soucis avec webpack : 
```
ERROR in ./src/sass/global.scss 1:0
Module parse failed: Unexpected character '@' (1:0)
You may need an appropriate loader to handle this file type.
> @charset "UTF-8";
| /*!
| * www.KNACSS.com v7.1.0 (october, 31 2018) @author: Alsacreations, Raphael Goetter
```
C'est apparement un problème d'un caractère ASCII qui traine dans les fichiers.
Bien relou le problème.

Merci pour votre aide.

**Comment by raphaelgoetter** [comment]
Hello,

Il semblerait que ce ne soit pas nouveau : 

- https://github.com/alsacreations/KNACSS/issues/203
- https://github.com/alsacreations/KNACSS/issues/197

Je vais voir ce que je peux faire de mon côté.

**Comment by darkiron** [comment]
ok merci ;)

**Comment by raphaelgoetter** [comment]
Disons que ce n'est pas du côté KNACSS que ça se passe a priori :/
