### ISSUE TITLE
Knacss et Gmap API v3

### ISSUE THREAD

**Issue by rair** [alsacreations/KNACSS#30]
Bonjour !

j'ai recontré un petit souci avec les infobulles (InfoWindow) de ggmap.
- absence de la croix de fermeture (juste 2px du bord gauche de l'image)
- débordement vertical des images contenues dans l'infobulle, par exemple les infobulles faites par gmap lui même sur des éléments cliquable de la carte, avec une preview de la streetview. (à noter qu'après fermeture et réouverture de l'infobulle, l'affichage était bon).

solutions trouvées
- problème de la croix résolu en ajoutant la règle .gm-style img {max-width : none;}
- problème des débordements d'images résolu en supprimant la règle img {height:auto;}

**Comment by raphaelgoetter** [comment]
Hop, je ré-ouvre ce sujet datant d'il y a presque 2 ans pour confirmer que la règle actuellement en place sur KNACSS, à savoir : 

```
/* Google Gmap3 bug fix on images */
.gm-style img {
  height: 100%;
}

:not(.gm-style) img {
  height: auto;
}
```

Est extrêmement contraignante car elle impose un `height: auto` sur toutes les images du document, avec un poids de sélecteur important de surcroît.

Il faut vraiment rendre cette règle optionnelle uniquement si Gmaps est employé.

D'ailleurs si ça se trouve, le problème a déjà été auto-résolu du côté de Gmaps (quelqu'un pourrait savoir ça ?)

**Comment by raphaelgoetter** [comment]
done

**Comment by PhilippeVay** [comment]
Une page statique avec utilisation de l'API GMaps 3? J'ai la version statique de [around the world](http://www.cma-cgm.com/local/france/agency/257/cma-cgm-agences-france-ho?brand=cmacgm&fullName=False) ouais :)

Plutôt que de mettre à jour l'archive, je vais plutôt récupérer le code et le script pour en faire une page de test. Les scripts de GMaps ont déjà causé 2 fois des problèmes dans KNACSS...
