### ISSUE TITLE
Créer un dossier /dist

### ISSUE THREAD

**Issue by Gaspacchio** [alsacreations/KNACSS#300]
Il faudrait adopter une structure standard d'organisation du projet, basée sur les autres frameworks populaires, et notamment le dossier `/dist`.

Ceci permettrait de standardiser un peu ce projet.

Des exemples d'organisation de dossiers :
- https://github.com/twbs/bootstrap
- https://github.com/zurb/foundation-sites

**Comment by raphaelgoetter** [comment]
Après réflexion, je ne suis pas sûr du réel intérêt en pratique : le dossier `dist` de bootstrap et foundation est composé de fichiers variés (CSS et JS), or dans le cas de KNACSS, seul du CSS est généré.

Si c'est pour transformer `/css/` en `/dist/css` je suis mitigé...

**Comment by Gaspacchio** [comment]
Il s'agirait uniquement de transformer le dossier `/css/` en `/dist/`, afin d'adopter la structure de dossiers des autres projets.
Ça permettrait de se rapprocher d'une structure à laquelle sont habitués la plupart des développeurs utilisant des frameworks CSS.

**Comment by raphaelgoetter** [comment]
J'affecte à la prochaine version (v8) de KNACSS
