### ISSUE TITLE
où retrouver les anciennes doc ?

### ISSUE THREAD

**Issue by MathieuDerelle** [alsacreations/KNACSS#306]
j'utilise KNACSS v6.1.2 dans un de mes projets.

le site https://www.knacss.com/doc.html ne montre que la doc de la v7

Comment peut-on retrouver l'ancienne doc ?

https://github.com/alsacreations/KNACSS/tree/v6/doc, I guess ?

**Comment by raphaelgoetter** [comment]
Bonsoir Mathieu,

Il est toujours possible de récupérer la "cheat sheet" v6 à cette adresse : https://www.knacss.com/assets/pdf/knacss6-cheatsheet.pdf

Il est également possible de parcourir les anciens repo github soit par branche soit par tag pour y retrouver la doc en effet : 
https://github.com/alsacreations/KNACSS/tree/6.1.2

Bonne chance :)

**Comment by MathieuDerelle** [comment]
merci
