### ISSUE TITLE
Knacss v8 TODO List

### ISSUE THREAD

**Issue by raphaelgoetter** [alsacreations/KNACSS#307]
_Document en cours de rédaction_

# Nouveautés 

- bla

# Suppressions

- Revoir le reset de KNACSS, et supprimer le fichier de reset Reboot pour éviter les conflits avec le fichier de base de KNACSS (https://github.com/alsacreations/KNACSS/issues/309)
- Vérifier si le fichier `wordpress.scss` est encore d'actualité (supprimer / mettre à jour)

# Améliorations

- Refondre les classes utilitaires (https://github.com/alsacreations/KNACSS/issues/311)
- renommer les classes `grid-` en `grillade-` pour éviter tout conflit (https://github.com/alsacreations/KNACSS/issues/308)
- revoir l'affichage des inputs (https://github.com/alsacreations/KNACSS/issues/310)
- placer les variables de composants dans chaque fichier de composant (https://github.com/alsacreations/KNACSS/issues/290)
- résoudre les problèmes de conflits de nommage (https://github.com/alsacreations/KNACSS/issues/270)
- améliorer la doc (https://github.com/alsacreations/KNACSS/issues/290). Faire un vrai styleguide maintenable

# Idées à piocher 

- https://tailwindcss.com/
- https://rsms.me/raster/
- https://bulma.io/

# Road to KNACSS v10 (car pas de v9)

- variables CSS et autres "CSSnext" ?

**Comment by IGLOU-EU** [comment]
Ce serait pas mal d'avoir des grillade- pour chaque 'Breakpoints' voir de pouvoir les cumuler  
`grillade-3-medium-1`, `grillade-3-medium-2-small-1` ou encore `grillade-3 grillade-medium-2 grillade-small-1`  
  
Non ? :)

**Comment by raphaelgoetter** [comment]
@IGLOU-EU en effet cela a été soulevé ici : https://github.com/alsacreations/KNACSS/issues/318

**Comment by parnissolle** [comment]
Petit up, je vois que le projet ne bouge plus beaucoup... Est-ce que le projet est encore maintenu ? La v8 est-elle toujours dans les cartons (possible release date) ?

**Comment by raphaelgoetter** [comment]
Hello,

La réponse est "oui et non". La version actuelle de KNACSS est au point mort et est en pleine refonte. On reprend tout à partir de zéro et on a créé un nouveau repo, pour l'instant hébergé ici : https://github.com/raphaelgoetter/knacss-reborn

**Comment by parnissolle** [comment]
Ah cool ! Merci je vais suivre ce projet 🙂

**Comment by Aylay** [comment]
Bonjour @raphaelgoetter ,

Pourquoi une refonte globale ainsi qu'un changement de repo ?

Merci & merci pour votre super travail !!!

**Comment by o314** [comment]
Salut !

Est ce que un projet comme https://cssinjs.org/ serait a considerer / aurait un impact sur l'evolution de knacss,
notamment au niveau des pre/post processeur css ?

**Comment by raphaelgoetter** [comment]
@Aylay Nous avions vraiment envie de nous recentrer sur notre usage de KNACSS. C'était au départ un outil parfaitement adapté à nos besoins que nous avons enrichi au fur et à mesure de fonctionnalités que nous n'utilisons même plus dans nos projets. Donc grosse remise en question et refonte intégrale. Pour l'instant le repo se trouve sur mon compte mais sera rapatrié sur le compte d'Alsacréations dès qu'il aura pris en maturité.

@o314 Je parle en mon nom et non à celui du reste de la team, mais pour moi la réponse est non : il n'est pas prévu de CSS-in-JS dans KNACSS dans les moutures prochaines.

**Comment by Aylay** [comment]
@raphaelgoetter 

Merci pour cette réponse bien complète. Si ce n'est pas indiscret, qu'utilisez vous à la place de KNACSS dans vos projets ?

Merci
Belle journée.

**Comment by raphaelgoetter** [comment]
Nous continuons à utiliser KNACSS, mais quasiment plus que pour les fichiers de base.

**Comment by Aylay** [comment]
Très bien.

Merci pour les informations.

N'hésitez pas à me dire quand tout sera bon ;)

**Comment by o314** [comment]
Merci egalement pour le retour

**Comment by raphaelgoetter** [comment]
Hello,

Rien n'est encore finalisé mais ça commence à ressembler à quelque chose...

- le repo : https://github.com/raphaelgoetter/knacss-reborn (le readme n'est pas encore à jour)
- la doc dans l'état actuel : https://www.knacss.com/doc-reborn.html

**Comment by raphaelgoetter** [comment]
Il fallait s'y attendre, l'histoire continue... ailleurs...

Né en 2012 et après près de 10 années de bons et loyaux services, le projet initial « KNACSS » d'Alsacréations laisse place à une toute nouvelle version, totalement remaniée : KNACSS Reborn.

Ce repo n'est plus maintenu est est dorénavant remplacé par celui de KNACSS Reborn : https://github.com/raphaelgoetter/knacss-reborn

**Comment by raphaelgoetter** [comment]
Pour faciliter les mises à jour et éviter d'embrouiller tout le monde, “Reborn” passe sur le repo historique de KNACSS sous forme de version majeure 8.
