### ISSUE TITLE
Revoir les techniques des inputs

### ISSUE THREAD

**Issue by raphaelgoetter** [alsacreations/KNACSS#310]
Il y a des bugs Safari notamment.

S'inspirer de ça ? https://codepen.io/oliviale/full/mgWjpq

**Comment by PhilippeVay** [comment]
Parmi les features et contraintes :

* Au moins styler :
  * input type text, checkbox, radio
  * select
  * textarea
  * button, input type button/submit (c'est une autre problématique ça)
* label et input peuvent être imbriqués ou accolés. Préférer imbriqué mais prévoir aussi l'autre cas quand un client a cette contrainte (si possible)
* pouvoir modifier KNACSS rapidement avec sa propre flèche de select, etc (placer ces configs en tête de fichier, pas en plein milieu d'une règle)
* styler les états `:hover`, `:focus` (et les 2 à la fois)
* styler `:disabled`
* prévoir l'état erreur (bordure rouge, message d'erreur correctement associé, éventuellement label en rouge)
* éventuellement prévoir "l'état info" (avec un bouton `(?)` à droite)
* IE11 et les SVG
* Safari est l'autre navigateur à bien tester (cf. #298 pas résolu)
* accessibilité : le contraste des éléments d'interface / UI doit être d'au moins 3:1 (rond des radio, coche, flèche des select, bordure des input ➡️  **tout** ce qui est graphique), sauf quand c'est désactivé (disabled)
* accessibilité : tester en Mode de Contraste Élevé (Windows et il y a maintenant un équivalent sous OS X)
* accessibilité : pour la démo, associer label et champ via les attributs `for` et `id` (et éventuellement ARIA pour certains états)

**Comment by raphaelgoetter** [comment]
Il fallait s'y attendre, l'histoire continue... ailleurs...

Né en 2012 et après près de 10 années de bons et loyaux services, le projet initial « KNACSS » d'Alsacréations laisse place à une toute nouvelle version, totalement remaniée : KNACSS Reborn.

Ce repo n'est plus maintenu est est dorénavant remplacé par celui de KNACSS Reborn : https://github.com/raphaelgoetter/knacss-reborn
