### ISSUE TITLE
grid-template-columns: repeat(21fr); }

### ISSUE THREAD

**Issue by marionb35** [alsacreations/KNACSS#315]

**Comment by marionb35** [comment]
Bonjour, J'ai un souci pour ma première utilisation de knacss.

le code ci-dessous ne semble pas bien se compiler :
```
 // grid constructor (.grid-2 to .grid-$cols)
@for $i from 2 through $cols {
  [class*="grid-#{$i}"] {
    grid-template-columns: repeat(#{$i}, 1fr);
  }
}

```
dans l'inspecteur de chrome ça m'écrit :

`[class*="grid-6"] {
    grid-template-columns: repeat(61fr);
}`

est-ce qu'il y a quelque chose que j'ai raté?

Merci d'avance,

**Comment by raphaelgoetter** [comment]
Je viens de tester rapidement en ligne sur Sassmeister et la compilation est bonne : 

![cols](https://user-images.githubusercontent.com/491029/61960062-1529f480-afc5-11e9-9233-8c46da1d9aa6.png)

Avec quel outil réalises-tu ta compilation ?

**Comment by marionb35** [comment]
Je passe via le plugin wordpress wp-scss

**Comment by marionb35** [comment]
effectivement en compilant via vs code et le terminal il n'y a pas de souci. c'est sans doute dû au plugin wp-scss

**Comment by raphaelgoetter** [comment]
Oui je crains que ce soit dû à ce plugin qui ne connaît sans doute pas encore Grid Layout. Tu as moyen d'ouvrir une issue là bas ?

**Comment by raphaelgoetter** [comment]
Il fallait s'y attendre, l'histoire continue... ailleurs...

Né en 2012 et après près de 10 années de bons et loyaux services, le projet initial « KNACSS » d'Alsacréations laisse place à une toute nouvelle version, totalement remaniée : KNACSS Reborn.

Ce repo n'est plus maintenu est est dorénavant remplacé par celui de KNACSS Reborn : https://github.com/raphaelgoetter/knacss-reborn
