### ISSUE TITLE
Gulp 3.9 - Gulp 4

### ISSUE THREAD

**Issue by raphaelgoetter** [alsacreations/KNACSS#317]
Le Gulpfile.js de KNACSS est conçu pour Gulp 3.9. Il ne fonctionne pas dans l'état avec Gulp 4.

En attendant de modifier les tâches du Gulpfile, il faut changer `gulp": "latest"` dans le fichier package.json et mettre en dur 3.9.0 (puisque sinon actuellement dès qu'on fait un `npm install/update` de KNACSS on installe forcément Gulp 4 et tout foire).

**Comment by robinparisi** [comment]
Hello,

De manière générale, il est beaucoup plus prudent de fixer le numéro des versions de tous les modules dans le package.json (avec le ^ et si la lib est sûre ou le ~ si elle l'est moins).

Concernant l'utilisation de Browserslist :

```
var browsersList = [
  '> 1%',
  'last 2 versions',
  'IE >= 10', 'Edge >= 16',
  'Chrome >= 60',
  'Firefox >= 50', 'Firefox ESR',
  'Safari >= 10',
  'ios_saf >= 10',
  'Android >= 5'
];
```

Cette configuration pose problème, car elle va "matcher" indéfiniment des navigateurs abandonnés. Tout est expliqué ici : https://jamie.build/last-2-versions

Pour l'utilisation dans le navigateur, le mieux reste de préciser uniquement le `%` d'utilisation ou d'utiliser le `not dead` dans le pire des cas : https://github.com/browserslist/browserslist#best-practices

**Comment by raphaelgoetter** [comment]
Oui tu as raison et nous allons prévoir ça aussi.

Pour ce qui est de Browserslist et des % de navigateurs, ce n'est pas idiot en effet. Mais la version IE demeure importante pour certains clients. On va peut-être simplifier la liste tout de même.

Merci à toi :)

**Comment by raphaelgoetter** [comment]
Modif prise en compte dans la future v8
