### ISSUE TITLE
Améliorations de Grillade

### ISSUE THREAD

**Issue by raphaelgoetter** [alsacreations/KNACSS#318]
Gérer les alignements ?

Gérer le rtl ?

Piocher des idées ici ? http://flexboxgrid.com/

**Comment by SkullMasher** [comment]
Pour moi les alignements définitivement. J'ajoute toujours un fichier helper avec des alignements supplémentaire space-between/around/evenly après inclusion de knacss.

**Comment by yannux** [comment]
Les classes du genre 
`col-xs-12, col-sm-8 , col-md-6, col-lg-4`
c'est plutôt pratique. 

Dans un autre genre un peu j'ai crée quelques class : grid-1-large-2, grid-1-medium-2-large-4, etc..  plutôt pratique dans certains cas.

**Comment by raphaelgoetter** [comment]
Je reste mitigé quand à l'accumulation de classes ou de variantes qui vont énormément alourdir l'outil.
Je crains d'en faire une usine à gaz, d'autant plus que grâce à Grid Layout, des "frameworks de grille" deviennent petit à petit moins pertinents.
J'y réfléchis...

**Comment by raphaelgoetter** [comment]
Il fallait s'y attendre, l'histoire continue... ailleurs...

Né en 2012 et après près de 10 années de bons et loyaux services, le projet initial « KNACSS » d'Alsacréations laisse place à une toute nouvelle version, totalement remaniée : KNACSS Reborn.

Ce repo n'est plus maintenu est est dorénavant remplacé par celui de KNACSS Reborn : https://github.com/raphaelgoetter/knacss-reborn
