### ISSUE TITLE
Dernière version stable : 7.1.0, 7.1.1 ou 7.1.2 ?

### ISSUE THREAD

**Issue by gizmecano** [alsacreations/KNACSS#321]
J'admets être un peu perdu dans les différentes versions les plus récentes du projet. En effet :

1. le [site du projet](https://www.knacss.com/) indique que la _dernière version majeure_ est la `7.1` datée d'octobre 2018, ce qui semble bien correspondre à la [publication de la _release_ `7.1.0`](https://github.com/alsacreations/KNACSS/releases/latest) du 31 octobre 2018.

2. si on télécharge le [projet depuis la page d'accueil du dépôt](https://github.com/alsacreations/KNACSS/archive/master.zip), on obtient une version `7.1.1` datée du 10 décembre 2018, laquelle semble ne jamais avoir été publiée en tant que _release_.

3. si on consulte le [fichier `changelog.md`](https://github.com/alsacreations/KNACSS/blob/master/changelog.md), on trouve mention d'une version `7.1.2` datée du 30 janvier 2019, alors qu'_a priori_ aucun fichier `knacss.css` ne porte un tel numéro de version.

Ne serait-il pas envisageable (voire souhaitable) de publier explicitement la dernière version stable en tant que [_release_](https://github.com/alsacreations/KNACSS/releases) ?

**Comment by raphaelgoetter** [comment]
Hello,

C'est une bonne remarque en effet, qui devrait être corrigée à présent.

L'explication vient du fait qu'on a commencé à travailler sur la version 8 du projet.

Bonne journée !

**Comment by gizmecano** [comment]
Bonjour @raphaelgoetter,

> L'explication vient du fait qu'on a commencé à travailler sur la version 8 du projet.

Effectivement, je l'avais compris en survolant #307 : c'est pour cette raison que je parlais de version _stable_ dans ma remarque précédente.

Merci beaucoup d'avoir réagit aussi rapidement (et un _vendredi_ en plus) en tout cas...

👏
