### ISSUE TITLE
.grid ou .grillade ?

### ISSUE THREAD

**Issue by P3ter** [alsacreations/KNACSS#322]
Bonjour,

Je test actuellement KNACSS en version 7.1.2 et j'ai remarqué que pour faire fonctionner le système de grille je dois utiliser les class `.grillade` et non `.grid`. Je me demande si je n'ai pas raté quelque chose, car il me semblait que ce renommage était prévus pour la version 8.

**Comment by raphaelgoetter** [comment]
Hello,

Ce n'est pas normal en effet. Je me renseigne.

**Comment by raphaelgoetter** [comment]
Je confirme qu'il y avait effectivement un souci concernant le tag `7.1.2` qui avait été pushé à partir de la branche v8 en cours de développement.
Un tag correctif `7.1.3` vient d'être pushé. Normalement tout est réglé.

**Comment by P3ter** [comment]
Je confirme que c'est OK en 7.1.3. Merci !
