### ISSUE TITLE
Question autour de l'imbrication d'éléments de grille

### ISSUE THREAD

**Issue by smonff** [alsacreations/KNACSS#327]
Bonjour et merci pour le travail autour de KNACSS.

Il y a un aspect de Grillade sur lequel je n'arrive pas à trouver de documentation: comment gérer l'imbrication de grilles? Est-il possible d'imbriquer les classes utilitaires de Grillade (`.grid`, `col-*`, etc.)? Je vois comment faire en n'utilisant pas le framework, mais mes tentatives d'imbrication en l'utilisant ne semblent pas avoir d'effet et je ne peux pas trouver de documentation.

Quel est le *pattern* recommandé pour cela?

Merci.

**Comment by raphaelgoetter** [comment]
Bonjour,

La documentation de Grillade se trouve ici : https://www.knacss.com/doc.html#grids 

Il n'est pas fait mention d'imbrications mais pour les avoir testées, un `.grid-*` peut parfaitement contenir lui-même un autre `.grid-*`.

Toutefois, et c'est un avis personnel, Grillade est un "framework" ultra simplifié et il ne devrait pas être employé pour des constructions complexes... où Grid Layout est aujourd'hui bien plus adapté.

Bon dimanche !

**Comment by smonff** [comment]
Je vais continuer d'expérimenter dans ce sens, ayant des besoins assez simples. En attendant d'être formé sur Grid Layout de façon plus complète, Grillade est bien pratique pour mettre en place des choses rapidemment. 

Merci pour cette réponse!
