### ISSUE TITLE
!global assignment depreciation

### ISSUE THREAD

**Issue by Hugo-Trentesaux** [alsacreations/KNACSS#328]
I installed knacss and got this warning at compilation:

```
DEPRECATION WARNING on line 27 of /home/hugo/dev/sass/knacss/_library/grillade-grid.scss:
!global assignments won't be able to declare new variables in future versions.
Consider adding `$gutter: null` at the top level.
```

Just wanted to tell ^^

(d'ailleurs, je me demande pourquoi je parle anglais, moi aussi je suis né à Strasbourg :laughing: )

**Comment by raphaelgoetter** [comment]
Il fallait s'y attendre, l'histoire continue... ailleurs...

Né en 2012 et après près de 10 années de bons et loyaux services, le projet initial « KNACSS » d'Alsacréations laisse place à une toute nouvelle version, totalement remaniée : KNACSS Reborn.

Ce repo n'est plus maintenu est est dorénavant remplacé par celui de KNACSS Reborn : https://github.com/raphaelgoetter/knacss-reborn
