### ISSUE TITLE
Où se trouve la documentation ?

### ISSUE THREAD

**Issue by Levure** [alsacreations/KNACSS#329]
Bonjour !

J'ai quelques corrections (mineures) à suggérer pour la documentation (https://www.knacss.com/doc.html), mais je me rends compte qu'elle ne se trouve pas dans ce repository (ou bien que j'ai mal cherché).

Se trouverait-t-elle dans un autre repository ?

D'avance merci ! ;-)

**Comment by raphaelgoetter** [comment]
Hello !

Cette doc n'est pas versionnée, c'est du simple HTML.

Une refonte complète de KNACSS est actuellement en projet, pour info.
