### ISSUE TITLE
Priorité des breakpoints dans les classes utilitaires

### ISSUE THREAD

**Issue by marjodu** [alsacreations/KNACSS#338]
Bonjour,

Je rencontre une difficulté avec les breakpoints et les classes utilitaires définies dans _variables.scss
Il me semble que les classes utilitaires sans préfixe breakpoint devraient avoir moins de poids que celles avec. Puis les breakpoints les plus grands devraient avoir la priorité sur les plus petits.

Un exemple :
`<div class="flex align-items-center md:align-items-start">`
A partir et au dessus du breakpoint md, align-items-start devrait être utilisé à la place de align-items-center.
Je ne parviens pas à obtenir ce résultat, l'utilitaire ayant le plus de poids est celui qui est défini le plus tard dans $utils de _variables.scss

Comment je peux obtenir ce résultat ? Merci d'avance !

**Comment by raphaelgoetter** [comment]
En effet c'est bien vu. Cela devrait être corrigé à présent sur le v8.0.3.

**Comment by marjodu** [comment]
Merci pour le retour rapide ! 
Ça fait tout à fait le travail !
