### ISSUE TITLE
Grillade, soucis de priorités des breakpoints

### ISSUE THREAD

**Issue by stephanegrenier** [alsacreations/KNACSS#339]
Bonjour,

les media query sont mal ordonnées dans le code généré pour les grillades
Je prends par exemple le cas des col-span
si on utilise dans un div md:col-span-2 et lg:col-span-1
lg:col-span-1 est définie avant md:col-span-2 et donc en > 1024 px on aura finalement col-span-2 au lieu de col-span-1

j'ai modifié le scss pour tester et ça semble marcher chez moi maintenant
je vous attache ce qui me semblerait être mieux (modulo que je n'ai jamais écrit de scss, je débute avec votre projet ^^)

j'ai renommé le .scss en .txt pour que l'upload soit valide
[grillade.txt](https://github.com/alsacreations/KNACSS/files/6368459/grillade.txt)

**Comment by raphaelgoetter** [comment]
Bonjour,

Quelle version de KNACSS avez-vous utilisée ?

Normalement ces soucis de priorités ont été résolus dans la version 8.0.3 suite à cette issue : https://github.com/alsacreations/KNACSS/issues/338

**Comment by stephanegrenier** [comment]
Bonjour, 

A priori j'utilise bien la 8.0.3
j'ai ça dans mon package.json:   
"_from": "knacss",
"_id": "knacss@8.0.3",

Et en regardant le code actuel il y a bien ce qui me pose soucis
@for $i from 1 through $grid-columns {
  @each $bp, $bpv in $breakpoints {
    @media (min-width: #{$bpv}) {

Pour moi ces 2 boucles devraient être interverties (en ajoutant l'init sans breakpoint à l'extérieur), pour chaque catégorie (grid-columns, spacers,...)
histoire d'avoir toutes les definitions dans un seul media query par breakpoints et donc avec les media query bien ordonnés
je verrai donc plus qqc comme ça:

@each $bp, $bpv in $breakpoints {  
  @media (min-width: #{$bpv}) {
    @for $i from 1 through $grid-columns {
  
Vous pouvez comparer mon fichier avec le votre, je pense que cela sera plus clair, notamment si vous générez les css

**Comment by raphaelgoetter** [comment]
Bonjour Stéphane,

Il y a en effet un souci, et votre fichier se rapproche de la solution.
Mais il y a encore des corrections à apporter car il produit des classes dupliquées inutilement (par ex. `.grid-cols-2 ` générée dans plusieurs media queries).

Je regarde en détail rapidement.

**Comment by raphaelgoetter** [comment]
Je vais tester cette version : https://gist.github.com/raphaelgoetter/af709e6bc683903592bd4b83ab383f03

**Comment by marjodu** [comment]
Bonjour, y a t'il eu du progrès sur cette question ? Je rencontre le même problème, précisément sur les col-span. En version 8.0.3 également.

**Comment by raphaelgoetter** [comment]
Oui, c'est corrigé sur la 8.0.4 👍 https://github.com/alsacreations/KNACSS/tree/v8.0.4
