### ISSUE TITLE
Exemple de la documentation

### ISSUE THREAD

**Issue by Meithal** [alsacreations/KNACSS#340]
J'ai voulu essayer knacss et mettre en place un jumbotron, voilà le resultat

![Capture d’écran 2021-11-26 213745](https://user-images.githubusercontent.com/12249929/143628526-1e4005af-575f-49a0-961f-85c72fe5de7c.png)

Comparé à bootstrap où la classe container et jumbotron fonctionnent sans surprise, ici le resultat est surprenant.

**Comment by raphaelgoetter** [comment]
Hello,

Merci pour ce retour.

En fait je ne connaissais pas le Jumbotron de Bootstrap, donc tu m'as permis de le découvrir, merci :)

Les classes `layout-maxed` et `layout-hero` fonctionnent de la même manière que [dans Bootstrap](https://getbootstrap.com/docs/4.0/components/jumbotron/) dans la mesure où elles ne peuvent pas à la fois être un conteneur et un contenu.

Dans ton exemple, ton paragraphe est à la fois conteneur (`layout-hero`) et contenu ("Salut à tous"). Pour que ton exemple fonctionne il faudrait séparer les deux : 

```html
< div class="layout-hero">
  <p class="text-center">Salut à tous</p>
</div>
```

C'est aussi de cette manière que fonctionne le Jumbotron de Bootstrap et c'est ce qui est présenté dans l'exemple en ligne proposé dans la documentation de KNACSS : https://codepen.io/raphaelgoetter/pen/RwrEKZr?editors=1100

Bon week-end !

**Comment by Meithal** [comment]
Ah merci ca marche parfaitement, méprise de ma part !

**Comment by raphaelgoetter** [comment]
Ah bah nickel alors ! :)

**Comment by raphaelgoetter** [comment]
Hello, j'ai mis la documentation à jour pour être plus clair concernant ces classes de Layout : https://www.knacss.com/doc.html#layout ;)
